/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Irys-Banner-Shapes-2.gltf -t 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    cubes_0: THREE.Mesh;
    cubes_2: THREE.Mesh;
    cubes_4: THREE.Mesh;
    cubes_6: THREE.Mesh;
    cubes_8: THREE.Mesh;
    cubes_10: THREE.Mesh;
    cubes_12: THREE.Mesh;
    cubes_14: THREE.Mesh;
    cubes_16: THREE.Mesh;
    cubes_18: THREE.Mesh;
    cubes_20: THREE.Mesh;
    cubes_22: THREE.Mesh;
    cubes_24: THREE.Mesh;
    cubes_26: THREE.Mesh;
    cubes_28: THREE.Mesh;
    cubes_30: THREE.Mesh;
    cubes_32: THREE.Mesh;
    cubes_34: THREE.Mesh;
    cubes_36: THREE.Mesh;
    cubes_38: THREE.Mesh;
    cubes_40: THREE.Mesh;
    cubes_42: THREE.Mesh;
    cubes_44: THREE.Mesh;
    cubes_46: THREE.Mesh;
    cubes_48: THREE.Mesh;
    cubes_50: THREE.Mesh;
    cubes_52: THREE.Mesh;
    cubes_54: THREE.Mesh;
    cubes_56: THREE.Mesh;
    cubes_58: THREE.Mesh;
    cubes_60: THREE.Mesh;
    cubes_62: THREE.Mesh;
    cubes_64: THREE.Mesh;
    cubes_66: THREE.Mesh;
    cubes_68: THREE.Mesh;
    cubes_70: THREE.Mesh;
    cubes_72: THREE.Mesh;
    cubes_74: THREE.Mesh;
    cubes_76: THREE.Mesh;
    cubes_78: THREE.Mesh;
    cubes_80: THREE.Mesh;
    cubes_82: THREE.Mesh;
    cubes_84: THREE.Mesh;
    cubes_86: THREE.Mesh;
    cubes_88: THREE.Mesh;
    cubes_90: THREE.Mesh;
    cubes_92: THREE.Mesh;
    cubes_94: THREE.Mesh;
    cubes_96: THREE.Mesh;
    cubes_98: THREE.Mesh;
    cubes_100: THREE.Mesh;
    cubes_102: THREE.Mesh;
    cubes_104: THREE.Mesh;
    cubes_106: THREE.Mesh;
    cubes_108: THREE.Mesh;
    cubes_110: THREE.Mesh;
    cubes_112: THREE.Mesh;
    cubes_114: THREE.Mesh;
    cubes_116: THREE.Mesh;
    cubes_118: THREE.Mesh;
    cubes_120: THREE.Mesh;
    cubes_122: THREE.Mesh;
    cubes_124: THREE.Mesh;
    cubes_126: THREE.Mesh;
    cubes_128: THREE.Mesh;
    cubes_130: THREE.Mesh;
    cubes_132: THREE.Mesh;
    cubes_134: THREE.Mesh;
    cubes_136: THREE.Mesh;
    cubes_138: THREE.Mesh;
    cubes_140: THREE.Mesh;
    cubes_142: THREE.Mesh;
    cubes_144: THREE.Mesh;
    cubes_146: THREE.Mesh;
    cubes_148: THREE.Mesh;
    cubes_150: THREE.Mesh;
    cubes_152: THREE.Mesh;
    cubes_154: THREE.Mesh;
    cubes_156: THREE.Mesh;
    cubes_158: THREE.Mesh;
    cubes_160: THREE.Mesh;
    cubes_162: THREE.Mesh;
    cubes_164: THREE.Mesh;
    cubes_166: THREE.Mesh;
    cubes_168: THREE.Mesh;
    cubes_170: THREE.Mesh;
    cubes_172: THREE.Mesh;
    cubes_174: THREE.Mesh;
    cubes_176: THREE.Mesh;
    cubes_178: THREE.Mesh;
    cubes_180: THREE.Mesh;
    cubes_182: THREE.Mesh;
    cubes_184: THREE.Mesh;
    cubes_186: THREE.Mesh;
    cubes_188: THREE.Mesh;
    cubes_190: THREE.Mesh;
    cubes_192: THREE.Mesh;
    cubes_194: THREE.Mesh;
    cubes_196: THREE.Mesh;
    cubes_198: THREE.Mesh;
    cubes_200: THREE.Mesh;
    cubes_202: THREE.Mesh;
    cubes_204: THREE.Mesh;
    cubes_206: THREE.Mesh;
    cubes_208: THREE.Mesh;
    cubes_210: THREE.Mesh;
    cubes_212: THREE.Mesh;
    cubes_214: THREE.Mesh;
    cubes_216: THREE.Mesh;
    cubes_218: THREE.Mesh;
    cubes_220: THREE.Mesh;
    cubes_222: THREE.Mesh;
    cubes_224: THREE.Mesh;
    cubes_226: THREE.Mesh;
    cubes_228: THREE.Mesh;
    cubes_230: THREE.Mesh;
    cubes_232: THREE.Mesh;
    cubes_234: THREE.Mesh;
    cubes_236: THREE.Mesh;
    cubes_238: THREE.Mesh;
    cubes_240: THREE.Mesh;
    cubes_242: THREE.Mesh;
    cubes_244: THREE.Mesh;
    cubes_246: THREE.Mesh;
    cubes_248: THREE.Mesh;
    cubes_250: THREE.Mesh;
    cubes_252: THREE.Mesh;
    cubes_254: THREE.Mesh;
    cubes_256: THREE.Mesh;
    cubes_258: THREE.Mesh;
    cubes_260: THREE.Mesh;
    cubes_262: THREE.Mesh;
    cubes_264: THREE.Mesh;
    cubes_266: THREE.Mesh;
    cubes_268: THREE.Mesh;
    cubes_270: THREE.Mesh;
    cubes_272: THREE.Mesh;
    cubes_274: THREE.Mesh;
    cubes_276: THREE.Mesh;
    cubes_278: THREE.Mesh;
    cubes_280: THREE.Mesh;
    cubes_282: THREE.Mesh;
    cubes_284: THREE.Mesh;
    cubes_286: THREE.Mesh;
    cubes_288: THREE.Mesh;
    cubes_290: THREE.Mesh;
    cubes_292: THREE.Mesh;
    cubes_294: THREE.Mesh;
    cubes_296: THREE.Mesh;
    cubes_298: THREE.Mesh;
    cubes_300: THREE.Mesh;
    cubes_302: THREE.Mesh;
    cubes_304: THREE.Mesh;
    cubes_306: THREE.Mesh;
    cubes_308: THREE.Mesh;
    cubes_310: THREE.Mesh;
    cubes_312: THREE.Mesh;
    cubes_314: THREE.Mesh;
    cubes_316: THREE.Mesh;
    cubes_318: THREE.Mesh;
    cubes_320: THREE.Mesh;
    cubes_322: THREE.Mesh;
    cubes_324: THREE.Mesh;
    cubes_326: THREE.Mesh;
    cubes_328: THREE.Mesh;
    cubes_330: THREE.Mesh;
    cubes_332: THREE.Mesh;
    cubes_334: THREE.Mesh;
    cubes_336: THREE.Mesh;
    cubes_338: THREE.Mesh;
    cubes_340: THREE.Mesh;
    cubes_342: THREE.Mesh;
    cubes_344: THREE.Mesh;
    cubes_346: THREE.Mesh;
    cubes_348: THREE.Mesh;
    cubes_350: THREE.Mesh;
    cubes_352: THREE.Mesh;
    cubes_354: THREE.Mesh;
    cubes_356: THREE.Mesh;
    cubes_358: THREE.Mesh;
    cubes_360: THREE.Mesh;
    cubes_362: THREE.Mesh;
    cubes_364: THREE.Mesh;
    cubes_366: THREE.Mesh;
    cubes_368: THREE.Mesh;
    cubes_370: THREE.Mesh;
    cubes_372: THREE.Mesh;
    cubes_374: THREE.Mesh;
    cubes_376: THREE.Mesh;
    cubes_378: THREE.Mesh;
    cubes_380: THREE.Mesh;
    cubes_382: THREE.Mesh;
    cubes_384: THREE.Mesh;
    cubes_386: THREE.Mesh;
    cubes_388: THREE.Mesh;
    cubes_390: THREE.Mesh;
    cubes_392: THREE.Mesh;
    cubes_394: THREE.Mesh;
    cubes_396: THREE.Mesh;
    cubes_398: THREE.Mesh;
    sphere_1: THREE.Mesh;
    sphere_3: THREE.Mesh;
    sphere_5: THREE.Mesh;
    sphere_7: THREE.Mesh;
    sphere_9: THREE.Mesh;
    sphere_11: THREE.Mesh;
    sphere_13: THREE.Mesh;
    sphere_15: THREE.Mesh;
    sphere_17: THREE.Mesh;
    sphere_19: THREE.Mesh;
    sphere_21: THREE.Mesh;
    sphere_23: THREE.Mesh;
    sphere_25: THREE.Mesh;
    sphere_27: THREE.Mesh;
    sphere_29: THREE.Mesh;
    sphere_31: THREE.Mesh;
    sphere_33: THREE.Mesh;
    sphere_35: THREE.Mesh;
    sphere_37: THREE.Mesh;
    sphere_39: THREE.Mesh;
    sphere_41: THREE.Mesh;
    sphere_43: THREE.Mesh;
    sphere_45: THREE.Mesh;
    sphere_47: THREE.Mesh;
    sphere_49: THREE.Mesh;
    sphere_51: THREE.Mesh;
    sphere_53: THREE.Mesh;
    sphere_55: THREE.Mesh;
    sphere_57: THREE.Mesh;
    sphere_59: THREE.Mesh;
    sphere_61: THREE.Mesh;
    sphere_63: THREE.Mesh;
    sphere_65: THREE.Mesh;
    sphere_67: THREE.Mesh;
    sphere_69: THREE.Mesh;
    sphere_71: THREE.Mesh;
    sphere_73: THREE.Mesh;
    sphere_75: THREE.Mesh;
    sphere_77: THREE.Mesh;
    sphere_79: THREE.Mesh;
    sphere_81: THREE.Mesh;
    sphere_83: THREE.Mesh;
    sphere_85: THREE.Mesh;
    sphere_87: THREE.Mesh;
    sphere_89: THREE.Mesh;
    sphere_91: THREE.Mesh;
    sphere_93: THREE.Mesh;
    sphere_95: THREE.Mesh;
    sphere_97: THREE.Mesh;
    sphere_99: THREE.Mesh;
    sphere_101: THREE.Mesh;
    sphere_103: THREE.Mesh;
    sphere_105: THREE.Mesh;
    sphere_107: THREE.Mesh;
    sphere_109: THREE.Mesh;
    sphere_111: THREE.Mesh;
    sphere_113: THREE.Mesh;
    sphere_115: THREE.Mesh;
    sphere_117: THREE.Mesh;
    sphere_119: THREE.Mesh;
    sphere_121: THREE.Mesh;
    sphere_123: THREE.Mesh;
    sphere_125: THREE.Mesh;
    sphere_127: THREE.Mesh;
    sphere_129: THREE.Mesh;
    sphere_131: THREE.Mesh;
    sphere_133: THREE.Mesh;
    sphere_135: THREE.Mesh;
    sphere_137: THREE.Mesh;
    sphere_139: THREE.Mesh;
    sphere_141: THREE.Mesh;
    sphere_143: THREE.Mesh;
    sphere_145: THREE.Mesh;
    sphere_147: THREE.Mesh;
    sphere_149: THREE.Mesh;
    sphere_151: THREE.Mesh;
    sphere_153: THREE.Mesh;
    sphere_155: THREE.Mesh;
    sphere_157: THREE.Mesh;
    sphere_159: THREE.Mesh;
    sphere_161: THREE.Mesh;
    sphere_163: THREE.Mesh;
    sphere_165: THREE.Mesh;
    sphere_167: THREE.Mesh;
    sphere_169: THREE.Mesh;
    sphere_171: THREE.Mesh;
    sphere_173: THREE.Mesh;
    sphere_175: THREE.Mesh;
    sphere_177: THREE.Mesh;
    sphere_179: THREE.Mesh;
    sphere_181: THREE.Mesh;
    sphere_183: THREE.Mesh;
    sphere_185: THREE.Mesh;
    sphere_187: THREE.Mesh;
    sphere_189: THREE.Mesh;
    sphere_191: THREE.Mesh;
    sphere_193: THREE.Mesh;
    sphere_195: THREE.Mesh;
    sphere_197: THREE.Mesh;
    sphere_199: THREE.Mesh;
    sphere_201: THREE.Mesh;
    sphere_203: THREE.Mesh;
    sphere_205: THREE.Mesh;
    sphere_207: THREE.Mesh;
    sphere_209: THREE.Mesh;
    sphere_211: THREE.Mesh;
    sphere_213: THREE.Mesh;
    sphere_215: THREE.Mesh;
    sphere_217: THREE.Mesh;
    sphere_219: THREE.Mesh;
    sphere_221: THREE.Mesh;
    sphere_223: THREE.Mesh;
    sphere_225: THREE.Mesh;
    sphere_227: THREE.Mesh;
    sphere_229: THREE.Mesh;
    sphere_231: THREE.Mesh;
    sphere_233: THREE.Mesh;
    sphere_235: THREE.Mesh;
    sphere_237: THREE.Mesh;
    sphere_239: THREE.Mesh;
    sphere_241: THREE.Mesh;
    sphere_243: THREE.Mesh;
    sphere_245: THREE.Mesh;
    sphere_247: THREE.Mesh;
    sphere_249: THREE.Mesh;
    sphere_251: THREE.Mesh;
    sphere_253: THREE.Mesh;
    sphere_255: THREE.Mesh;
    sphere_257: THREE.Mesh;
    sphere_259: THREE.Mesh;
    sphere_261: THREE.Mesh;
    sphere_263: THREE.Mesh;
    sphere_265: THREE.Mesh;
    sphere_267: THREE.Mesh;
    sphere_269: THREE.Mesh;
    sphere_271: THREE.Mesh;
    sphere_273: THREE.Mesh;
    sphere_275: THREE.Mesh;
    sphere_277: THREE.Mesh;
    sphere_279: THREE.Mesh;
    sphere_281: THREE.Mesh;
    sphere_283: THREE.Mesh;
    sphere_285: THREE.Mesh;
    sphere_287: THREE.Mesh;
    sphere_289: THREE.Mesh;
    sphere_291: THREE.Mesh;
    sphere_293: THREE.Mesh;
    sphere_295: THREE.Mesh;
    sphere_297: THREE.Mesh;
    sphere_299: THREE.Mesh;
    sphere_301: THREE.Mesh;
    sphere_303: THREE.Mesh;
    sphere_305: THREE.Mesh;
    sphere_307: THREE.Mesh;
    sphere_309: THREE.Mesh;
    sphere_311: THREE.Mesh;
    sphere_313: THREE.Mesh;
    sphere_315: THREE.Mesh;
    sphere_317: THREE.Mesh;
    sphere_319: THREE.Mesh;
    sphere_321: THREE.Mesh;
    sphere_323: THREE.Mesh;
    sphere_325: THREE.Mesh;
    sphere_327: THREE.Mesh;
    sphere_329: THREE.Mesh;
    sphere_331: THREE.Mesh;
    sphere_333: THREE.Mesh;
    sphere_335: THREE.Mesh;
    sphere_337: THREE.Mesh;
    sphere_339: THREE.Mesh;
    sphere_341: THREE.Mesh;
    sphere_343: THREE.Mesh;
    sphere_345: THREE.Mesh;
    sphere_347: THREE.Mesh;
    sphere_349: THREE.Mesh;
    sphere_351: THREE.Mesh;
    sphere_353: THREE.Mesh;
    sphere_355: THREE.Mesh;
    sphere_357: THREE.Mesh;
    sphere_359: THREE.Mesh;
    sphere_361: THREE.Mesh;
    sphere_363: THREE.Mesh;
    sphere_365: THREE.Mesh;
    sphere_367: THREE.Mesh;
    sphere_369: THREE.Mesh;
    sphere_371: THREE.Mesh;
    sphere_373: THREE.Mesh;
    sphere_375: THREE.Mesh;
    sphere_377: THREE.Mesh;
    sphere_379: THREE.Mesh;
    sphere_381: THREE.Mesh;
    sphere_383: THREE.Mesh;
    sphere_385: THREE.Mesh;
    sphere_387: THREE.Mesh;
    sphere_389: THREE.Mesh;
    sphere_391: THREE.Mesh;
    sphere_393: THREE.Mesh;
    sphere_395: THREE.Mesh;
    sphere_397: THREE.Mesh;
    sphere_399: THREE.Mesh;
  };
  materials: {
    ["Objects Shader"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ActionName = "";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function IrysBannerShapes2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/Irys-Banner-Shapes-2.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={10000000000}
        near={0.01}
        fov={23.249}
        position={[0, 0, 7.822]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={10000000000}
        near={0.01}
        fov={23.249}
        position={[-1.486, -0.753, 3.8]}
      />
      <mesh
        geometry={nodes.cubes_0.geometry}
        material={materials["Objects Shader"]}
        position={[-0.944, 0.42, 0.001]}
        rotation={[-1.47, -0.343, -0.804]}
        scale={1.056}
      />
      <mesh
        geometry={nodes.cubes_2.geometry}
        material={materials["Objects Shader"]}
        position={[-0.817, 0.565, -0.054]}
        rotation={[-1.117, 0.361, 0.82]}
        scale={1.271}
      />
      <mesh
        geometry={nodes.cubes_4.geometry}
        material={materials["Objects Shader"]}
        position={[-0.806, 0.329, -0.092]}
        rotation={[-1.473, 1.212, 0.573]}
        scale={1.124}
      />
      <mesh
        geometry={nodes.cubes_6.geometry}
        material={materials["Objects Shader"]}
        position={[-1.098, 0.334, -0.047]}
        rotation={[-1.633, 0.226, 0.589]}
        scale={0.72}
      />
      <mesh
        geometry={nodes.cubes_8.geometry}
        material={materials["Objects Shader"]}
        position={[-0.681, 0.405, 0.029]}
        rotation={[-1.523, -0.126, 0.123]}
        scale={0.607}
      />
      <mesh
        geometry={nodes.cubes_10.geometry}
        material={materials["Objects Shader"]}
        position={[-1.178, 0.52, -0.114]}
        rotation={[-2.477, 0.844, 1.211]}
        scale={1.068}
      />
      <mesh
        geometry={nodes.cubes_12.geometry}
        material={materials["Objects Shader"]}
        position={[-1.041, 0.208, -0.094]}
        rotation={[-1.106, 0.571, -1.181]}
        scale={0.919}
      />
      <mesh
        geometry={nodes.cubes_14.geometry}
        material={materials["Objects Shader"]}
        position={[-0.909, 0.16, -0.033]}
        rotation={[-1.136, 0.024, -0.522]}
        scale={0.707}
      />
      <mesh
        geometry={nodes.cubes_16.geometry}
        material={materials["Objects Shader"]}
        position={[-1.085, 0.435, -0.088]}
        rotation={[-2.164, -0.083, -1.012]}
        scale={1.002}
      />
      <mesh
        geometry={nodes.cubes_18.geometry}
        material={materials["Objects Shader"]}
        position={[-0.882, 0.021, -0.053]}
        rotation={[-1.207, -0.139, -0.173]}
        scale={1.087}
      />
      <mesh
        geometry={nodes.cubes_20.geometry}
        material={materials["Objects Shader"]}
        position={[-1.174, 0.27, -0.078]}
        rotation={[-1.649, 0.825, 0.522]}
        scale={1.313}
      />
      <mesh
        geometry={nodes.cubes_22.geometry}
        material={materials["Objects Shader"]}
        position={[-0.859, 0.108, -0.02]}
        rotation={[-1.705, 0.941, -0.112]}
        scale={1.354}
      />
      <mesh
        geometry={nodes.cubes_24.geometry}
        material={materials["Objects Shader"]}
        position={[-1.149, 0.19, -0.051]}
        rotation={[-2.272, 0.693, 0.804]}
        scale={1.165}
      />
      <mesh
        geometry={nodes.cubes_26.geometry}
        material={materials["Objects Shader"]}
        position={[-0.883, 0.238, 0.016]}
        rotation={[-1.197, 0.284, 0.493]}
        scale={0.774}
      />
      <mesh
        geometry={nodes.cubes_28.geometry}
        material={materials["Objects Shader"]}
        position={[-0.811, 0.005, -0.04]}
        rotation={[-1.617, 1.019, -0.215]}
        scale={0.976}
      />
      <mesh
        geometry={nodes.cubes_30.geometry}
        material={materials["Objects Shader"]}
        position={[-0.786, -0.055, 0.009]}
        rotation={[-1.941, -0.922, 0.52]}
        scale={1.109}
      />
      <mesh
        geometry={nodes.cubes_32.geometry}
        material={materials["Objects Shader"]}
        position={[-1.009, -0.12, 0.035]}
        rotation={[-0.999, -1.097, 0.753]}
        scale={0.611}
      />
      <mesh
        geometry={nodes.cubes_34.geometry}
        material={materials["Objects Shader"]}
        position={[-0.897, 0.124, -0.071]}
        rotation={[-1.354, -0.58, -0.074]}
        scale={0.722}
      />
      <mesh
        geometry={nodes.cubes_36.geometry}
        material={materials["Objects Shader"]}
        position={[-1.232, -0.182, 0.002]}
        rotation={[-2.015, -0.888, -1.035]}
        scale={0.602}
      />
      <mesh
        geometry={nodes.cubes_38.geometry}
        material={materials["Objects Shader"]}
        position={[-1.076, -0.093, 0.086]}
        rotation={[-2.331, -0.687, -1.19]}
        scale={1.391}
      />
      <mesh
        geometry={nodes.cubes_40.geometry}
        material={materials["Objects Shader"]}
        position={[-0.897, -0.083, 0.106]}
        rotation={[-1.289, 0.392, -0.522]}
        scale={1.392}
      />
      <mesh
        geometry={nodes.cubes_42.geometry}
        material={materials["Objects Shader"]}
        position={[-1.256, -0.009, 0.036]}
        rotation={[-1.366, -0.409, -0.147]}
        scale={1.196}
      />
      <mesh
        geometry={nodes.cubes_44.geometry}
        material={materials["Objects Shader"]}
        position={[-1.095, -0.321, -0.004]}
        rotation={[-1.994, 0.547, 0.211]}
        scale={1.013}
      />
      <mesh
        geometry={nodes.cubes_46.geometry}
        material={materials["Objects Shader"]}
        position={[-0.725, -0.277, -0.018]}
        rotation={[-1.385, -0.214, -0.286]}
        scale={0.867}
      />
      <mesh
        geometry={nodes.cubes_48.geometry}
        material={materials["Objects Shader"]}
        position={[-1.045, -0.213, 0.017]}
        rotation={[-1.234, -0.691, 0.318]}
        scale={0.745}
      />
      <mesh
        geometry={nodes.cubes_50.geometry}
        material={materials["Objects Shader"]}
        position={[-0.897, -0.242, 0.065]}
        rotation={[-1.74, -0.057, -0.678]}
        scale={0.955}
      />
      <mesh
        geometry={nodes.cubes_52.geometry}
        material={materials["Objects Shader"]}
        position={[-1.002, -0.235, 0.05]}
        rotation={[-1.861, 0.127, 0.084]}
        scale={0.749}
      />
      <mesh
        geometry={nodes.cubes_54.geometry}
        material={materials["Objects Shader"]}
        position={[-0.855, -0.415, 0.042]}
        rotation={[-1.394, -0.174, -0.895]}
        scale={1.218}
      />
      <mesh
        geometry={nodes.cubes_56.geometry}
        material={materials["Objects Shader"]}
        position={[-0.713, -0.4, 0.022]}
        rotation={[-1.303, -0.114, -0.891]}
        scale={0.838}
      />
      <mesh
        geometry={nodes.cubes_58.geometry}
        material={materials["Objects Shader"]}
        position={[-0.881, -0.308, 0.072]}
        rotation={[-2.05, 0.159, 0.137]}
        scale={1.173}
      />
      <mesh
        geometry={nodes.cubes_60.geometry}
        material={materials["Objects Shader"]}
        position={[-0.843, -0.203, -0.007]}
        rotation={[-0.852, -1.05, 0.38]}
        scale={1.169}
      />
      <mesh
        geometry={nodes.cubes_62.geometry}
        material={materials["Objects Shader"]}
        position={[-0.908, -0.559, 0.048]}
        rotation={[-1.451, -0.164, 0.438]}
        scale={1.215}
      />
      <mesh
        geometry={nodes.cubes_64.geometry}
        material={materials["Objects Shader"]}
        position={[-0.963, -0.537, -0.039]}
        rotation={[-1.605, -0.085, -0.382]}
        scale={1.219}
      />
      <mesh
        geometry={nodes.cubes_66.geometry}
        material={materials["Objects Shader"]}
        position={[-0.777, -0.728, 0.052]}
        rotation={[-1.771, -0.701, 0.035]}
        scale={0.859}
      />
      <mesh
        geometry={nodes.cubes_68.geometry}
        material={materials["Objects Shader"]}
        position={[-0.965, -0.636, -0.018]}
        rotation={[-1.424, 0.04, 0.78]}
        scale={0.644}
      />
      <mesh
        geometry={nodes.cubes_70.geometry}
        material={materials["Objects Shader"]}
        position={[-0.996, -0.466, -0.013]}
        rotation={[-1.463, 0.23, -0.29]}
        scale={0.689}
      />
      <mesh
        geometry={nodes.cubes_72.geometry}
        material={materials["Objects Shader"]}
        position={[-0.822, -0.838, 0.066]}
        rotation={[-1.948, -1.523, -0.783]}
        scale={1.16}
      />
      <mesh
        geometry={nodes.cubes_74.geometry}
        material={materials["Objects Shader"]}
        position={[-0.857, -0.581, -0.013]}
        rotation={[-1.569, -0.857, 0.34]}
        scale={1.384}
      />
      <mesh
        geometry={nodes.cubes_76.geometry}
        material={materials["Objects Shader"]}
        position={[-0.695, -0.729, 0.027]}
        rotation={[-1.251, 0.162, -0.2]}
        scale={1.059}
      />
      <mesh
        geometry={nodes.cubes_78.geometry}
        material={materials["Objects Shader"]}
        position={[-0.697, -0.978, 0.143]}
        rotation={[-1.825, -1.364, 0.491]}
        scale={0.804}
      />
      <mesh
        geometry={nodes.cubes_80.geometry}
        material={materials["Objects Shader"]}
        position={[-0.885, -0.641, 0.099]}
        rotation={[-1.296, -0.334, -0.12]}
        scale={0.705}
      />
      <mesh
        geometry={nodes.cubes_82.geometry}
        material={materials["Objects Shader"]}
        position={[-0.651, -0.612, 0.081]}
        rotation={[-1.64, 0.145, -0.515]}
        scale={0.898}
      />
      <mesh
        geometry={nodes.cubes_84.geometry}
        material={materials["Objects Shader"]}
        position={[-0.536, -0.814, 0.094]}
        rotation={[-2.605, -1.346, 0.064]}
        scale={1.005}
      />
      <mesh
        geometry={nodes.cubes_86.geometry}
        material={materials["Objects Shader"]}
        position={[-0.655, -0.848, -0.021]}
        rotation={[-2.422, -1.004, 0.337]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.cubes_88.geometry}
        material={materials["Objects Shader"]}
        position={[-0.853, -0.721, 0.045]}
        rotation={[-1.644, -0.294, 0.013]}
        scale={1.218}
      />
      <mesh
        geometry={nodes.cubes_90.geometry}
        material={materials["Objects Shader"]}
        position={[-0.858, -0.848, 0.125]}
        rotation={[-2.786, -1.356, -0.784]}
        scale={1.054}
      />
      <mesh
        geometry={nodes.cubes_92.geometry}
        material={materials["Objects Shader"]}
        position={[-0.591, -0.712, 0.175]}
        rotation={[-1.782, -0.11, -0.165]}
        scale={1.28}
      />
      <mesh
        geometry={nodes.cubes_94.geometry}
        material={materials["Objects Shader"]}
        position={[-0.521, -0.707, 0.065]}
        rotation={[2.23, -0.966, -1.821]}
        scale={1.201}
      />
      <mesh
        geometry={nodes.cubes_96.geometry}
        material={materials["Objects Shader"]}
        position={[-0.558, -1.016, 0.008]}
        rotation={[-0.858, -1.198, 0.768]}
        scale={0.628}
      />
      <mesh
        geometry={nodes.cubes_98.geometry}
        material={materials["Objects Shader"]}
        position={[-0.43, -0.541, 0.071]}
        rotation={[0.454, -1.306, 1.873]}
        scale={1.228}
      />
      <mesh
        geometry={nodes.cubes_100.geometry}
        material={materials["Objects Shader"]}
        position={[-0.431, -0.722, 0.01]}
        rotation={[1.71, -1.134, -2.276]}
        scale={1.082}
      />
      <mesh
        geometry={nodes.cubes_102.geometry}
        material={materials["Objects Shader"]}
        position={[-0.404, -0.774, 0.075]}
        rotation={[-1.272, -1.263, 0.635]}
        scale={1.119}
      />
      <mesh
        geometry={nodes.cubes_104.geometry}
        material={materials["Objects Shader"]}
        position={[-0.292, -0.673, 0.069]}
        rotation={[-1.255, -0.157, 0.844]}
        scale={0.977}
      />
      <mesh
        geometry={nodes.cubes_106.geometry}
        material={materials["Objects Shader"]}
        position={[-0.264, -1.109, 0.169]}
        rotation={[-1.906, -0.804, 0.137]}
        scale={1.046}
      />
      <mesh
        geometry={nodes.cubes_108.geometry}
        material={materials["Objects Shader"]}
        position={[-0.322, -0.782, 0.116]}
        rotation={[0.629, -1.083, 1.891]}
        scale={0.909}
      />
      <mesh
        geometry={nodes.cubes_110.geometry}
        material={materials["Objects Shader"]}
        position={[-0.435, -1.153, 0.141]}
        rotation={[1.824, -0.976, -2.927]}
        scale={1.192}
      />
      <mesh
        geometry={nodes.cubes_112.geometry}
        material={materials["Objects Shader"]}
        position={[-0.454, -0.893, 0.153]}
        rotation={[-1.522, -0.554, -0.598]}
        scale={1.068}
      />
      <mesh
        geometry={nodes.cubes_114.geometry}
        material={materials["Objects Shader"]}
        position={[-0.395, -1.086, 0.093]}
        rotation={[-2.602, -1.041, -0.392]}
        scale={0.799}
      />
      <mesh
        geometry={nodes.cubes_116.geometry}
        material={materials["Objects Shader"]}
        position={[-0.239, -0.77, 0.144]}
        rotation={[-0.053, -1.417, 2.562]}
        scale={0.952}
      />
      <mesh
        geometry={nodes.cubes_118.geometry}
        material={materials["Objects Shader"]}
        position={[-0.343, -1.172, 0.104]}
        rotation={[-0.089, -1.411, 1.32]}
        scale={0.624}
      />
      <mesh
        geometry={nodes.cubes_120.geometry}
        material={materials["Objects Shader"]}
        position={[-0.105, -0.812, 0.005]}
        rotation={[-1.474, -0.519, -0.15]}
        scale={0.609}
      />
      <mesh
        geometry={nodes.cubes_122.geometry}
        material={materials["Objects Shader"]}
        position={[-0.123, -0.678, 0.104]}
        rotation={[3.082, -1.122, -2.509]}
        scale={1.37}
      />
      <mesh
        geometry={nodes.cubes_124.geometry}
        material={materials["Objects Shader"]}
        position={[0.106, -1.134, 0.098]}
        rotation={[2.375, -1.013, -1.829]}
        scale={1.399}
      />
      <mesh
        geometry={nodes.cubes_126.geometry}
        material={materials["Objects Shader"]}
        position={[-0.194, -1.027, 0.064]}
        rotation={[-2.577, -1.199, -0.889]}
        scale={0.68}
      />
      <mesh
        geometry={nodes.cubes_128.geometry}
        material={materials["Objects Shader"]}
        position={[-0.162, -1.131, 0.175]}
        rotation={[0.837, -1.192, 1.56]}
        scale={0.661}
      />
      <mesh
        geometry={nodes.cubes_130.geometry}
        material={materials["Objects Shader"]}
        position={[-0.059, -1.14, 0.064]}
        rotation={[1.156, -0.888, 2.278]}
        scale={1.252}
      />
      <mesh
        geometry={nodes.cubes_132.geometry}
        material={materials["Objects Shader"]}
        position={[0.107, -1.008, 0.009]}
        rotation={[-0.661, -0.97, 1.78]}
        scale={0.624}
      />
      <mesh
        geometry={nodes.cubes_134.geometry}
        material={materials["Objects Shader"]}
        position={[0.185, -0.971, 0.057]}
        rotation={[0.494, -1.265, 1.154]}
        scale={0.663}
      />
      <mesh
        geometry={nodes.cubes_136.geometry}
        material={materials["Objects Shader"]}
        position={[0.213, -1.087, 0.128]}
        rotation={[-1.019, -0.89, 0.218]}
        scale={1.186}
      />
      <mesh
        geometry={nodes.cubes_138.geometry}
        material={materials["Objects Shader"]}
        position={[0.218, -0.966, -0.003]}
        rotation={[-2.127, -1.252, -1.439]}
        scale={1.073}
      />
      <mesh
        geometry={nodes.cubes_140.geometry}
        material={materials["Objects Shader"]}
        position={[0.211, -0.856, -0.065]}
        rotation={[1.957, -0.631, -2.455]}
        scale={0.888}
      />
      <mesh
        geometry={nodes.cubes_142.geometry}
        material={materials["Objects Shader"]}
        position={[-0.062, -1.159, -0.022]}
        rotation={[1.816, -1.033, 2.463]}
        scale={1.383}
      />
      <mesh
        geometry={nodes.cubes_144.geometry}
        material={materials["Objects Shader"]}
        position={[0.09, -0.772, 0.04]}
        rotation={[-1.918, -0.601, -0.837]}
        scale={1.295}
      />
      <mesh
        geometry={nodes.cubes_146.geometry}
        material={materials["Objects Shader"]}
        position={[0.096, -1.176, 0.155]}
        rotation={[-2.59, -1.423, -1.583]}
        scale={1.219}
      />
      <mesh
        geometry={nodes.cubes_148.geometry}
        material={materials["Objects Shader"]}
        position={[0.135, -1.088, 0.023]}
        rotation={[-1.818, -1.224, -0.066]}
        scale={0.735}
      />
      <mesh
        geometry={nodes.cubes_150.geometry}
        material={materials["Objects Shader"]}
        position={[0.194, -1.229, 0.227]}
        rotation={[-2.782, -1.178, -1.421]}
        scale={0.928}
      />
      <mesh
        geometry={nodes.cubes_152.geometry}
        material={materials["Objects Shader"]}
        position={[0.302, -0.964, 0.091]}
        rotation={[1.757, -1.233, -2.334]}
        scale={1.39}
      />
      <mesh
        geometry={nodes.cubes_154.geometry}
        material={materials["Objects Shader"]}
        position={[0.349, -0.749, 0.043]}
        rotation={[-2.215, -1.24, 0.486]}
        scale={1.349}
      />
      <mesh
        geometry={nodes.cubes_156.geometry}
        material={materials["Objects Shader"]}
        position={[0.581, -1.007, 0.15]}
        rotation={[1.941, -0.051, -3.074]}
        scale={1.29}
      />
      <mesh
        geometry={nodes.cubes_158.geometry}
        material={materials["Objects Shader"]}
        position={[0.313, -1.189, 0.146]}
        rotation={[1.592, -0.951, -2.107]}
        scale={1.138}
      />
      <mesh
        geometry={nodes.cubes_160.geometry}
        material={materials["Objects Shader"]}
        position={[0.468, -0.756, 0.011]}
        rotation={[2.165, -1.352, -2.383]}
        scale={0.815}
      />
      <mesh
        geometry={nodes.cubes_162.geometry}
        material={materials["Objects Shader"]}
        position={[0.508, -0.895, 0.092]}
        rotation={[1.195, -0.416, -2.496]}
        scale={1.026}
      />
      <mesh
        geometry={nodes.cubes_164.geometry}
        material={materials["Objects Shader"]}
        position={[0.48, -1.048, 0.201]}
        rotation={[1.896, -0.417, 3.039]}
        scale={0.853}
      />
      <mesh
        geometry={nodes.cubes_166.geometry}
        material={materials["Objects Shader"]}
        position={[0.264, -0.707, 0.023]}
        rotation={[-0.364, -1.169, 1.548]}
        scale={0.777}
      />
      <mesh
        geometry={nodes.cubes_168.geometry}
        material={materials["Objects Shader"]}
        position={[0.535, -0.708, -0.016]}
        rotation={[0.949, -0.637, 3.091]}
        scale={0.603}
      />
      <mesh
        geometry={nodes.cubes_170.geometry}
        material={materials["Objects Shader"]}
        position={[0.706, -1.004, 0.034]}
        rotation={[1.953, -0.955, -2.092]}
        scale={0.631}
      />
      <mesh
        geometry={nodes.cubes_172.geometry}
        material={materials["Objects Shader"]}
        position={[0.807, -0.975, 0.107]}
        rotation={[0.843, -0.848, 2.678]}
      />
      <mesh
        geometry={nodes.cubes_174.geometry}
        material={materials["Objects Shader"]}
        position={[0.68, -0.901, 0.054]}
        rotation={[-2.162, -1.346, -1.042]}
      />
      <mesh
        geometry={nodes.cubes_176.geometry}
        material={materials["Objects Shader"]}
        position={[0.682, -0.954, 0.112]}
        rotation={[1.318, -0.79, 2.69]}
        scale={0.921}
      />
      <mesh
        geometry={nodes.cubes_178.geometry}
        material={materials["Objects Shader"]}
        position={[0.632, -0.465, 0.007]}
        rotation={[-0.002, -1.091, 2.032]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.cubes_180.geometry}
        material={materials["Objects Shader"]}
        position={[0.571, -0.788, 0.065]}
        rotation={[0.957, -0.119, 2.064]}
        scale={0.974}
      />
      <mesh
        geometry={nodes.cubes_182.geometry}
        material={materials["Objects Shader"]}
        position={[0.684, -0.733, 0.03]}
        rotation={[1.629, -0.417, -2.141]}
        scale={0.733}
      />
      <mesh
        geometry={nodes.cubes_184.geometry}
        material={materials["Objects Shader"]}
        position={[1.035, -0.693, 0.076]}
        rotation={[1.407, -0.841, 2.932]}
        scale={1.216}
      />
      <mesh
        geometry={nodes.cubes_186.geometry}
        material={materials["Objects Shader"]}
        position={[0.623, -0.583, 0.09]}
        rotation={[2.496, -1.432, -2.537]}
        scale={0.895}
      />
      <mesh
        geometry={nodes.cubes_188.geometry}
        material={materials["Objects Shader"]}
        position={[0.772, -0.594, 0.062]}
        rotation={[1.527, 0.213, 2.589]}
        scale={1.191}
      />
      <mesh
        geometry={nodes.cubes_190.geometry}
        material={materials["Objects Shader"]}
        position={[0.958, -0.566, 0.085]}
        rotation={[2.001, -0.52, -3.114]}
        scale={1.139}
      />
      <mesh
        geometry={nodes.cubes_192.geometry}
        material={materials["Objects Shader"]}
        position={[0.567, -0.537, -0.004]}
        rotation={[2.806, -1.289, -2.116]}
        scale={0.665}
      />
      <mesh
        geometry={nodes.cubes_194.geometry}
        material={materials["Objects Shader"]}
        position={[0.968, -0.532, 0.063]}
        rotation={[0.987, -1.288, 2.934]}
        scale={1.322}
      />
      <mesh
        geometry={nodes.cubes_196.geometry}
        material={materials["Objects Shader"]}
        position={[1.051, -0.545, 0.007]}
        rotation={[1.243, -0.041, -3.02]}
        scale={0.626}
      />
      <mesh
        geometry={nodes.cubes_198.geometry}
        material={materials["Objects Shader"]}
        position={[1.077, -0.59, 0.073]}
        rotation={[1.362, -0.187, -3.056]}
        scale={0.791}
      />
      <mesh
        geometry={nodes.cubes_200.geometry}
        material={materials["Objects Shader"]}
        position={[1.168, -0.491, 0.053]}
        rotation={[1.971, -0.096, 2.925]}
        scale={1.321}
      />
      <mesh
        geometry={nodes.cubes_202.geometry}
        material={materials["Objects Shader"]}
        position={[0.916, -0.781, 0.065]}
        rotation={[-0.346, -1.095, 1.373]}
        scale={1.159}
      />
      <mesh
        geometry={nodes.cubes_204.geometry}
        material={materials["Objects Shader"]}
        position={[1.197, -0.354, 0.024]}
        rotation={[2.006, -1.165, -1.898]}
        scale={0.919}
      />
      <mesh
        geometry={nodes.cubes_206.geometry}
        material={materials["Objects Shader"]}
        position={[0.806, -0.522, 0.031]}
        rotation={[2.703, -1.244, -1.422]}
        scale={0.744}
      />
      <mesh
        geometry={nodes.cubes_208.geometry}
        material={materials["Objects Shader"]}
        position={[1.027, -0.315, 0.056]}
        rotation={[1.083, -0.152, 2.847]}
        scale={1.157}
      />
      <mesh
        geometry={nodes.cubes_210.geometry}
        material={materials["Objects Shader"]}
        position={[1.087, -0.456, 0.061]}
        rotation={[1.238, 0.332, -2.608]}
        scale={1.223}
      />
      <mesh
        geometry={nodes.cubes_212.geometry}
        material={materials["Objects Shader"]}
        position={[0.875, -0.452, 0.065]}
        rotation={[1.266, -0.636, -2.436]}
        scale={1.165}
      />
      <mesh
        geometry={nodes.cubes_214.geometry}
        material={materials["Objects Shader"]}
        position={[0.913, -0.156, 0.051]}
        rotation={[0.937, -0.853, 2.194]}
        scale={1.108}
      />
      <mesh
        geometry={nodes.cubes_216.geometry}
        material={materials["Objects Shader"]}
        position={[0.819, -0.204, 0.071]}
        rotation={[1.59, -0.287, -2.307]}
        scale={1.017}
      />
      <mesh
        geometry={nodes.cubes_218.geometry}
        material={materials["Objects Shader"]}
        position={[1.254, -0.094, 0.042]}
        rotation={[1.097, -0.277, 2.525]}
        scale={1.385}
      />
      <mesh
        geometry={nodes.cubes_220.geometry}
        material={materials["Objects Shader"]}
        position={[0.889, -0.29, -0.02]}
        rotation={[1.427, 0.573, -2.925]}
        scale={1.016}
      />
      <mesh
        geometry={nodes.cubes_222.geometry}
        material={materials["Objects Shader"]}
        position={[1.104, -0.359, 0.033]}
        rotation={[1.863, -0.845, -1.915]}
        scale={1.119}
      />
      <mesh
        geometry={nodes.cubes_224.geometry}
        material={materials["Objects Shader"]}
        position={[0.927, 0.048, -0.061]}
        rotation={[1.55, 0.503, -3.051]}
        scale={0.659}
      />
      <mesh
        geometry={nodes.cubes_226.geometry}
        material={materials["Objects Shader"]}
        position={[1.151, -0.14, 0.037]}
        rotation={[1.588, 0.397, 2.597]}
        scale={1.188}
      />
      <mesh
        geometry={nodes.cubes_228.geometry}
        material={materials["Objects Shader"]}
        position={[0.806, -0.122, -0.047]}
        rotation={[1.319, 0.239, 2.4]}
        scale={0.876}
      />
      <mesh
        geometry={nodes.cubes_230.geometry}
        material={materials["Objects Shader"]}
        position={[1.054, 0.212, 0.026]}
        rotation={[1.537, 0.319, -2.527]}
        scale={1.112}
      />
      <mesh
        geometry={nodes.cubes_232.geometry}
        material={materials["Objects Shader"]}
        position={[1.034, 0.02, 0.056]}
        rotation={[1.057, 0.051, -2.236]}
        scale={0.706}
      />
      <mesh
        geometry={nodes.cubes_234.geometry}
        material={materials["Objects Shader"]}
        position={[0.925, 0.032, -0.069]}
        rotation={[1.107, -0.846, 2.25]}
        scale={0.774}
      />
      <mesh
        geometry={nodes.cubes_236.geometry}
        material={materials["Objects Shader"]}
        position={[0.72, 0.096, 0.019]}
        rotation={[1.246, -0.344, 2.034]}
        scale={0.797}
      />
      <mesh
        geometry={nodes.cubes_238.geometry}
        material={materials["Objects Shader"]}
        position={[0.852, 0.104, 0.053]}
        rotation={[1.731, -0.754, 2.722]}
        scale={0.789}
      />
      <mesh
        geometry={nodes.cubes_240.geometry}
        material={materials["Objects Shader"]}
        position={[1.228, 0.05, -0.055]}
        rotation={[2, 0.16, -2.73]}
        scale={0.889}
      />
      <mesh
        geometry={nodes.cubes_242.geometry}
        material={materials["Objects Shader"]}
        position={[1.051, 0.064, 0.05]}
        rotation={[1.018, -0.177, 2.635]}
        scale={1.302}
      />
      <mesh
        geometry={nodes.cubes_244.geometry}
        material={materials["Objects Shader"]}
        position={[1.095, 0.217, -0.008]}
        rotation={[0.977, -0.547, -2.551]}
        scale={1.276}
      />
      <mesh
        geometry={nodes.cubes_246.geometry}
        material={materials["Objects Shader"]}
        position={[0.986, 0.328, -0.011]}
        rotation={[0.987, -0.377, 2.451]}
        scale={0.995}
      />
      <mesh
        geometry={nodes.cubes_248.geometry}
        material={materials["Objects Shader"]}
        position={[0.7, 0.343, -0.029]}
        rotation={[0.97, 0.549, 3.136]}
        scale={0.997}
      />
      <mesh
        geometry={nodes.cubes_250.geometry}
        material={materials["Objects Shader"]}
        position={[0.693, 0.099, -0.093]}
        rotation={[1.266, -0.198, -3.037]}
        scale={0.871}
      />
      <mesh
        geometry={nodes.cubes_252.geometry}
        material={materials["Objects Shader"]}
        position={[0.921, 0.375, -0.058]}
        rotation={[1.113, 1.028, -2.871]}
        scale={1.154}
      />
      <mesh
        geometry={nodes.cubes_254.geometry}
        material={materials["Objects Shader"]}
        position={[0.769, 0.405, -0.038]}
        rotation={[0.975, 0.147, -2.461]}
        scale={0.991}
      />
      <mesh
        geometry={nodes.cubes_256.geometry}
        material={materials["Objects Shader"]}
        position={[0.667, 0.257, -0.067]}
        rotation={[1.093, 1.002, -1.95]}
        scale={1.32}
      />
      <mesh
        geometry={nodes.cubes_258.geometry}
        material={materials["Objects Shader"]}
        position={[0.86, 0.2, -0.05]}
        rotation={[1.458, 0.289, -2.143]}
        scale={1.144}
      />
      <mesh
        geometry={nodes.cubes_260.geometry}
        material={materials["Objects Shader"]}
        position={[0.907, 0.303, 0.034]}
        rotation={[0.819, 0.823, -1.792]}
        scale={0.61}
      />
      <mesh
        geometry={nodes.cubes_262.geometry}
        material={materials["Objects Shader"]}
        position={[0.889, 0.575, -0.059]}
        rotation={[1.277, -0.04, 2.891]}
        scale={0.82}
      />
      <mesh
        geometry={nodes.cubes_264.geometry}
        material={materials["Objects Shader"]}
        position={[0.629, 0.435, -0.077]}
        rotation={[1.157, 0.61, 3.066]}
        scale={1.001}
      />
      <mesh
        geometry={nodes.cubes_266.geometry}
        material={materials["Objects Shader"]}
        position={[0.78, 0.576, -0.113]}
        rotation={[1.738, 0.421, 2.581]}
        scale={0.665}
      />
      <mesh
        geometry={nodes.cubes_268.geometry}
        material={materials["Objects Shader"]}
        position={[0.961, 0.501, -0.003]}
        rotation={[1.479, -0.471, 3.1]}
        scale={1.261}
      />
      <mesh
        geometry={nodes.cubes_270.geometry}
        material={materials["Objects Shader"]}
        position={[0.772, 0.725, -0.041]}
        rotation={[2.198, 1.015, 2.011]}
        scale={0.784}
      />
      <mesh
        geometry={nodes.cubes_272.geometry}
        material={materials["Objects Shader"]}
        position={[0.891, 0.571, 0.031]}
        rotation={[1.458, -0.047, -3.079]}
        scale={0.678}
      />
      <mesh
        geometry={nodes.cubes_274.geometry}
        material={materials["Objects Shader"]}
        position={[0.639, 0.713, -0.107]}
        rotation={[1.861, 0.619, -2.568]}
        scale={1.285}
      />
      <mesh
        geometry={nodes.cubes_276.geometry}
        material={materials["Objects Shader"]}
        position={[0.558, 0.507, 0.001]}
        rotation={[-2.328, 1.191, -0.377]}
        scale={0.954}
      />
      <mesh
        geometry={nodes.cubes_278.geometry}
        material={materials["Objects Shader"]}
        position={[0.932, 0.775, -0.092]}
        rotation={[0.961, 0.523, -1.877]}
        scale={1.214}
      />
      <mesh
        geometry={nodes.cubes_280.geometry}
        material={materials["Objects Shader"]}
        position={[0.815, 0.811, -0.042]}
        rotation={[1.338, 0.591, -2.436]}
        scale={0.635}
      />
      <mesh
        geometry={nodes.cubes_282.geometry}
        material={materials["Objects Shader"]}
        position={[0.522, 0.746, -0.017]}
        rotation={[-2.441, 1.193, 0.634]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.cubes_284.geometry}
        material={materials["Objects Shader"]}
        position={[0.736, 0.691, -0.08]}
        rotation={[-2.917, 1.365, 0.269]}
        scale={0.869}
      />
      <mesh
        geometry={nodes.cubes_286.geometry}
        material={materials["Objects Shader"]}
        position={[0.615, 0.832, -0.014]}
        rotation={[2.435, 0.987, -2.962]}
        scale={0.942}
      />
      <mesh
        geometry={nodes.cubes_288.geometry}
        material={materials["Objects Shader"]}
        position={[0.815, 0.796, -0.076]}
        rotation={[-2.263, 1.208, 1.445]}
        scale={0.846}
      />
      <mesh
        geometry={nodes.cubes_290.geometry}
        material={materials["Objects Shader"]}
        position={[0.797, 0.889, -0.112]}
        rotation={[0.895, 1.094, -2.671]}
        scale={0.788}
      />
      <mesh
        geometry={nodes.cubes_292.geometry}
        material={materials["Objects Shader"]}
        position={[0.64, 0.633, -0.005]}
        rotation={[1.276, 0.953, -2.075]}
        scale={0.912}
      />
      <mesh
        geometry={nodes.cubes_294.geometry}
        material={materials["Objects Shader"]}
        position={[0.387, 0.732, 0.023]}
        rotation={[-0.82, 1.555, -1.325]}
        scale={0.873}
      />
      <mesh
        geometry={nodes.cubes_296.geometry}
        material={materials["Objects Shader"]}
        position={[0.553, 0.986, -0.097]}
        rotation={[-1.947, 1.221, 0.327]}
        scale={1.322}
      />
      <mesh
        geometry={nodes.cubes_298.geometry}
        material={materials["Objects Shader"]}
        position={[0.449, 0.896, -0.052]}
        rotation={[1.407, 0.816, -2.685]}
        scale={1.098}
      />
      <mesh
        geometry={nodes.cubes_300.geometry}
        material={materials["Objects Shader"]}
        position={[0.647, 1.025, -0.137]}
        rotation={[-2.322, 1.005, -0.431]}
        scale={1.011}
      />
      <mesh
        geometry={nodes.cubes_302.geometry}
        material={materials["Objects Shader"]}
        position={[0.41, 0.824, 0.023]}
        rotation={[0.52, 0.979, -2.325]}
        scale={0.656}
      />
      <mesh
        geometry={nodes.cubes_304.geometry}
        material={materials["Objects Shader"]}
        position={[0.51, 0.762, -0.067]}
        rotation={[1.466, 0.188, -2.89]}
        scale={1.159}
      />
      <mesh
        geometry={nodes.cubes_306.geometry}
        material={materials["Objects Shader"]}
        position={[0.298, 1.021, -0.183]}
        rotation={[1.511, 0.365, 2.906]}
        scale={1.107}
      />
      <mesh
        geometry={nodes.cubes_308.geometry}
        material={materials["Objects Shader"]}
        position={[0.406, 1.223, -0.185]}
        rotation={[1.586, 0.62, 2.798]}
        scale={1.118}
      />
      <mesh
        geometry={nodes.cubes_310.geometry}
        material={materials["Objects Shader"]}
        position={[0.189, 0.784, 0.001]}
        rotation={[1.069, 0.273, 2.898]}
        scale={1.258}
      />
      <mesh
        geometry={nodes.cubes_312.geometry}
        material={materials["Objects Shader"]}
        position={[0.335, 0.922, -0.106]}
        rotation={[0.569, 1.391, -1.479]}
        scale={1.087}
      />
      <mesh
        geometry={nodes.cubes_314.geometry}
        material={materials["Objects Shader"]}
        position={[0.14, 1.06, -0.063]}
        rotation={[1.935, 0.582, 2.991]}
        scale={1.223}
      />
      <mesh
        geometry={nodes.cubes_316.geometry}
        material={materials["Objects Shader"]}
        position={[0.331, 0.753, -0.152]}
        rotation={[0.955, 0.249, -2.8]}
        scale={0.7}
      />
      <mesh
        geometry={nodes.cubes_318.geometry}
        material={materials["Objects Shader"]}
        position={[0.221, 1.08, -0.113]}
        rotation={[-2.236, 0.861, 0.788]}
        scale={0.635}
      />
      <mesh
        geometry={nodes.cubes_320.geometry}
        material={materials["Objects Shader"]}
        position={[0.411, 0.981, -0.1]}
        rotation={[-2.78, 1.184, 1.707]}
        scale={0.71}
      />
      <mesh
        geometry={nodes.cubes_322.geometry}
        material={materials["Objects Shader"]}
        position={[0.159, 1.248, -0.179]}
        rotation={[2.282, 1.116, -3.042]}
        scale={1.191}
      />
      <mesh
        geometry={nodes.cubes_324.geometry}
        material={materials["Objects Shader"]}
        position={[0.28, 1.224, -0.194]}
        rotation={[0.99, 0.323, -2.969]}
        scale={0.938}
      />
      <mesh
        geometry={nodes.cubes_326.geometry}
        material={materials["Objects Shader"]}
        position={[0.047, 1.213, -0.184]}
        rotation={[-1.175, 0.517, -0.485]}
        scale={0.9}
      />
      <mesh
        geometry={nodes.cubes_328.geometry}
        material={materials["Objects Shader"]}
        position={[0.099, 0.869, -0.157]}
        rotation={[-2.049, 0.953, 1.174]}
        scale={0.861}
      />
      <mesh
        geometry={nodes.cubes_330.geometry}
        material={materials["Objects Shader"]}
        position={[-0.008, 1.144, -0.094]}
        rotation={[0.602, 1.046, -1.617]}
        scale={0.614}
      />
      <mesh
        geometry={nodes.cubes_332.geometry}
        material={materials["Objects Shader"]}
        position={[-0.251, 1.103, -0.078]}
        rotation={[1.78, 0.909, 3.044]}
        scale={0.825}
      />
      <mesh
        geometry={nodes.cubes_334.geometry}
        material={materials["Objects Shader"]}
        position={[-0.122, 1.055, -0.118]}
        rotation={[-1.302, 0.505, -0.385]}
        scale={0.604}
      />
      <mesh
        geometry={nodes.cubes_336.geometry}
        material={materials["Objects Shader"]}
        position={[-0.152, 1.034, -0.043]}
        rotation={[-1.337, 0.914, -0.084]}
        scale={0.644}
      />
      <mesh
        geometry={nodes.cubes_338.geometry}
        material={materials["Objects Shader"]}
        position={[-0.258, 0.716, -0.05]}
        rotation={[-2.672, 0.982, 0.348]}
        scale={1.377}
      />
      <mesh
        geometry={nodes.cubes_340.geometry}
        material={materials["Objects Shader"]}
        position={[0.032, 1.121, -0.151]}
        rotation={[-2.849, 1.09, 0.828]}
        scale={0.764}
      />
      <mesh
        geometry={nodes.cubes_342.geometry}
        material={materials["Objects Shader"]}
        position={[-0.211, 1.097, -0.004]}
        rotation={[1.054, 0.978, 2.992]}
        scale={0.896}
      />
      <mesh
        geometry={nodes.cubes_344.geometry}
        material={materials["Objects Shader"]}
        position={[-0.061, 0.917, -0.099]}
        rotation={[-1.409, 0.616, 0.756]}
        scale={1.181}
      />
      <mesh
        geometry={nodes.cubes_346.geometry}
        material={materials["Objects Shader"]}
        position={[-0.453, 1.092, -0.164]}
        rotation={[-1.916, 1.096, -0.757]}
        scale={0.769}
      />
      <mesh
        geometry={nodes.cubes_348.geometry}
        material={materials["Objects Shader"]}
        position={[-0.357, 1.081, -0.038]}
        rotation={[-2.473, 1.349, 1.301]}
        scale={0.86}
      />
      <mesh
        geometry={nodes.cubes_350.geometry}
        material={materials["Objects Shader"]}
        position={[-0.163, 0.843, -0.101]}
        rotation={[0.867, 1.041, -1.966]}
        scale={0.806}
      />
      <mesh
        geometry={nodes.cubes_352.geometry}
        material={materials["Objects Shader"]}
        position={[-0.227, 0.799, -0.055]}
        rotation={[-1.231, 0.804, -0.357]}
        scale={0.861}
      />
      <mesh
        geometry={nodes.cubes_354.geometry}
        material={materials["Objects Shader"]}
        position={[-0.35, 1.022, -0.093]}
        rotation={[-1.92, 0.798, 1.043]}
        scale={0.899}
      />
      <mesh
        geometry={nodes.cubes_356.geometry}
        material={materials["Objects Shader"]}
        position={[-0.344, 0.835, -0.069]}
        rotation={[-2.131, 0.814, -0.463]}
        scale={1.121}
      />
      <mesh
        geometry={nodes.cubes_358.geometry}
        material={materials["Objects Shader"]}
        position={[-0.386, 0.742, -0.096]}
        rotation={[-1.353, 0.792, 0.109]}
        scale={0.809}
      />
      <mesh
        geometry={nodes.cubes_360.geometry}
        material={materials["Objects Shader"]}
        position={[-0.419, 0.613, -0.058]}
        rotation={[-2.362, 1.431, 1.229]}
        scale={1.286}
      />
      <mesh
        geometry={nodes.cubes_362.geometry}
        material={materials["Objects Shader"]}
        position={[-0.395, 0.938, -0.14]}
        rotation={[0.644, 0.934, -2.191]}
        scale={0.828}
      />
      <mesh
        geometry={nodes.cubes_364.geometry}
        material={materials["Objects Shader"]}
        position={[-0.354, 0.844, -0.066]}
        rotation={[-1.505, 0.331, -0.447]}
        scale={1.154}
      />
      <mesh
        geometry={nodes.cubes_366.geometry}
        material={materials["Objects Shader"]}
        position={[-0.617, 0.837, -0.061]}
        rotation={[-1.532, 0.111, 0.138]}
        scale={1.101}
      />
      <mesh
        geometry={nodes.cubes_368.geometry}
        material={materials["Objects Shader"]}
        position={[-0.771, 0.942, -0.141]}
        rotation={[-1.881, 0.587, 0.58]}
        scale={0.717}
      />
      <mesh
        geometry={nodes.cubes_370.geometry}
        material={materials["Objects Shader"]}
        position={[-0.67, 0.928, -0.037]}
        rotation={[-1.644, 1.212, -0.56]}
        scale={0.98}
      />
      <mesh
        geometry={nodes.cubes_372.geometry}
        material={materials["Objects Shader"]}
        position={[-0.713, 0.86, -0.177]}
        rotation={[-2.579, 1.004, 0.981]}
        scale={0.962}
      />
      <mesh
        geometry={nodes.cubes_374.geometry}
        material={materials["Objects Shader"]}
        position={[-0.625, 0.721, -0.074]}
        rotation={[2.886, 1.282, 2.05]}
        scale={0.971}
      />
      <mesh
        geometry={nodes.cubes_376.geometry}
        material={materials["Objects Shader"]}
        position={[-0.8, 0.765, -0.012]}
        rotation={[2.7, 1.128, 1.141]}
        scale={0.622}
      />
      <mesh
        geometry={nodes.cubes_378.geometry}
        material={materials["Objects Shader"]}
        position={[-0.54, 0.67, -0.048]}
        rotation={[-2, 1.006, 0.244]}
        scale={0.673}
      />
      <mesh
        geometry={nodes.cubes_380.geometry}
        material={materials["Objects Shader"]}
        position={[-0.773, 0.645, -0.024]}
        rotation={[-2.066, 0.189, -0.456]}
        scale={1.239}
      />
      <mesh
        geometry={nodes.cubes_382.geometry}
        material={materials["Objects Shader"]}
        position={[-0.819, 0.531, -0.066]}
        rotation={[-1.882, -0.428, -0.227]}
        scale={0.868}
      />
      <mesh
        geometry={nodes.cubes_384.geometry}
        material={materials["Objects Shader"]}
        position={[-0.878, 0.865, -0.068]}
        rotation={[-2.336, 1.104, 0.896]}
        scale={1.321}
      />
      <mesh
        geometry={nodes.cubes_386.geometry}
        material={materials["Objects Shader"]}
        position={[-0.556, 0.524, -0.072]}
        rotation={[0.409, 1.031, -1.964]}
        scale={0.735}
      />
      <mesh
        geometry={nodes.cubes_388.geometry}
        material={materials["Objects Shader"]}
        position={[-0.717, 0.74, -0.064]}
        rotation={[-1.267, 0.843, -0.376]}
        scale={0.769}
      />
      <mesh
        geometry={nodes.cubes_390.geometry}
        material={materials["Objects Shader"]}
        position={[-0.916, 0.502, -0.054]}
        rotation={[-1.532, 0.156, 0.918]}
        scale={0.779}
      />
      <mesh
        geometry={nodes.cubes_392.geometry}
        material={materials["Objects Shader"]}
        position={[-1.078, 0.579, -0.077]}
        rotation={[-1.771, 0.31, -0.952]}
        scale={1.138}
      />
      <mesh
        geometry={nodes.cubes_394.geometry}
        material={materials["Objects Shader"]}
        position={[-0.801, 0.42, 0.018]}
        rotation={[-1.311, 0.742, -0.611]}
        scale={0.83}
      />
      <mesh
        geometry={nodes.cubes_396.geometry}
        material={materials["Objects Shader"]}
        position={[-1.01, 0.568, -0.067]}
        rotation={[-1.113, 0.703, -0.083]}
        scale={1.324}
      />
      <mesh
        geometry={nodes.cubes_398.geometry}
        material={materials["Objects Shader"]}
        position={[-0.909, 0.693, -0.099]}
        rotation={[-1.97, -0.089, -0.069]}
        scale={1.299}
      />
      <mesh
        geometry={nodes.sphere_1.geometry}
        material={materials["Objects Shader"]}
        position={[-0.644, 0.5, -0.012]}
        rotation={[-1.646, 0.978, 0.626]}
        scale={0.97}
      />
      <mesh
        geometry={nodes.sphere_3.geometry}
        material={materials["Objects Shader"]}
        position={[-0.839, 0.276, 0.055]}
        rotation={[-1.041, 0.579, -0.83]}
        scale={1.348}
      />
      <mesh
        geometry={nodes.sphere_5.geometry}
        material={materials["Objects Shader"]}
        position={[-0.882, 0.465, 0.013]}
        rotation={[-1.117, 0.636, -0.264]}
        scale={0.835}
      />
      <mesh
        geometry={nodes.sphere_7.geometry}
        material={materials["Objects Shader"]}
        position={[-0.732, 0.355, -0.027]}
        rotation={[-1.686, 0.268, -0.578]}
        scale={0.658}
      />
      <mesh
        geometry={nodes.sphere_9.geometry}
        material={materials["Objects Shader"]}
        position={[-1.016, 0.456, -0.082]}
        rotation={[-0.87, 0.846, -1.448]}
        scale={1.026}
      />
      <mesh
        geometry={nodes.sphere_11.geometry}
        material={materials["Objects Shader"]}
        position={[-0.896, 0.379, -0.058]}
        rotation={[-1.992, -0.222, 0.431]}
        scale={0.667}
      />
      <mesh
        geometry={nodes.sphere_13.geometry}
        material={materials["Objects Shader"]}
        position={[-1.017, 0.14, 0.046]}
        rotation={[-2.032, 0.129, 0.55]}
        scale={0.892}
      />
      <mesh
        geometry={nodes.sphere_15.geometry}
        material={materials["Objects Shader"]}
        position={[-1.128, 0.415, -0.053]}
        rotation={[-2.352, 0.872, 0.398]}
        scale={0.617}
      />
      <mesh
        geometry={nodes.sphere_17.geometry}
        material={materials["Objects Shader"]}
        position={[-1.177, 0.457, -0.001]}
        rotation={[-1.534, 0.402, 0.288]}
        scale={1.384}
      />
      <mesh
        geometry={nodes.sphere_19.geometry}
        material={materials["Objects Shader"]}
        position={[-0.708, 0.089, -0.095]}
        rotation={[-1.608, -0.834, -0.083]}
        scale={0.933}
      />
      <mesh
        geometry={nodes.sphere_21.geometry}
        material={materials["Objects Shader"]}
        position={[-0.961, 0.301, -0.098]}
        rotation={[-1.979, 0.264, -0.688]}
        scale={1.133}
      />
      <mesh
        geometry={nodes.sphere_23.geometry}
        material={materials["Objects Shader"]}
        position={[-0.751, 0.126, -0.006]}
        rotation={[-2.109, -0.075, -0.052]}
        scale={1.289}
      />
      <mesh
        geometry={nodes.sphere_25.geometry}
        material={materials["Objects Shader"]}
        position={[-1.01, -0.009, -0.084]}
        rotation={[-1.498, -0.095, 0.365]}
        scale={1.368}
      />
      <mesh
        geometry={nodes.sphere_27.geometry}
        material={materials["Objects Shader"]}
        position={[-1.021, 0.144, -0.01]}
        rotation={[-1.437, 0.103, -0.288]}
        scale={1.38}
      />
      <mesh
        geometry={nodes.sphere_29.geometry}
        material={materials["Objects Shader"]}
        position={[-1.276, -0.082, 0.065]}
        rotation={[-2.205, -0.677, 0.531]}
        scale={0.92}
      />
      <mesh
        geometry={nodes.sphere_31.geometry}
        material={materials["Objects Shader"]}
        position={[-0.901, -0.058, 0.059]}
        rotation={[-1.951, -0.787, -0.448]}
        scale={0.687}
      />
      <mesh
        geometry={nodes.sphere_33.geometry}
        material={materials["Objects Shader"]}
        position={[-1.197, 0.114, 0.045]}
        rotation={[-1.543, -0.176, 0.726]}
        scale={0.607}
      />
      <mesh
        geometry={nodes.sphere_35.geometry}
        material={materials["Objects Shader"]}
        position={[-1.192, 0.017, 0.014]}
        rotation={[-1.657, -0.426, 0.871]}
        scale={1.096}
      />
      <mesh
        geometry={nodes.sphere_37.geometry}
        material={materials["Objects Shader"]}
        position={[-1.1, 0.02, -0.058]}
        rotation={[-1.374, -0.948, -0.319]}
        scale={0.663}
      />
      <mesh
        geometry={nodes.sphere_39.geometry}
        material={materials["Objects Shader"]}
        position={[-1.112, 0.102, -0.067]}
        rotation={[-2.085, 0.194, -0.549]}
        scale={0.658}
      />
      <mesh
        geometry={nodes.sphere_41.geometry}
        material={materials["Objects Shader"]}
        position={[-0.978, -0.223, 0.034]}
        rotation={[-1.926, 0.582, 0.68]}
        scale={0.895}
      />
      <mesh
        geometry={nodes.sphere_43.geometry}
        material={materials["Objects Shader"]}
        position={[-0.95, -0.165, -0.002]}
        rotation={[-2.055, 0.033, 0.45]}
        scale={0.758}
      />
      <mesh
        geometry={nodes.sphere_45.geometry}
        material={materials["Objects Shader"]}
        position={[-1.123, -0.029, 0.037]}
        rotation={[-1.173, -0.225, -0.671]}
        scale={0.83}
      />
      <mesh
        geometry={nodes.sphere_47.geometry}
        material={materials["Objects Shader"]}
        position={[-1.164, -0.169, -0.046]}
        rotation={[-1.704, -0.148, -0.588]}
        scale={1.369}
      />
      <mesh
        geometry={nodes.sphere_49.geometry}
        material={materials["Objects Shader"]}
        position={[-1.082, -0.261, -0.009]}
        rotation={[-1.441, -0.526, 0.432]}
        scale={0.748}
      />
      <mesh
        geometry={nodes.sphere_51.geometry}
        material={materials["Objects Shader"]}
        position={[-0.779, -0.301, 0.022]}
        rotation={[-1.733, -0.826, 0.757]}
        scale={1.068}
      />
      <mesh
        geometry={nodes.sphere_53.geometry}
        material={materials["Objects Shader"]}
        position={[-0.731, -0.166, -0.05]}
        rotation={[-1.49, -0.455, -0.775]}
        scale={0.852}
      />
      <mesh
        geometry={nodes.sphere_55.geometry}
        material={materials["Objects Shader"]}
        position={[-0.737, -0.356, 0.082]}
        rotation={[-2.319, -1.103, -0.795]}
        scale={1.289}
      />
      <mesh
        geometry={nodes.sphere_57.geometry}
        material={materials["Objects Shader"]}
        position={[-1.011, -0.398, -0.009]}
        rotation={[-1.421, 0.067, 0.157]}
        scale={1.067}
      />
      <mesh
        geometry={nodes.sphere_59.geometry}
        material={materials["Objects Shader"]}
        position={[-0.904, -0.405, 0.038]}
        rotation={[-2.033, -0.232, 0.367]}
        scale={1.084}
      />
      <mesh
        geometry={nodes.sphere_61.geometry}
        material={materials["Objects Shader"]}
        position={[-0.707, -0.483, 0.031]}
        rotation={[-2.044, -0.48, 0.711]}
        scale={1.139}
      />
      <mesh
        geometry={nodes.sphere_63.geometry}
        material={materials["Objects Shader"]}
        position={[-0.758, -0.532, 0.091]}
        rotation={[2.848, -1.237, -2.516]}
        scale={1.074}
      />
      <mesh
        geometry={nodes.sphere_65.geometry}
        material={materials["Objects Shader"]}
        position={[-0.808, -0.47, 0.069]}
        rotation={[-1.147, -0.398, 1.094]}
        scale={1.098}
      />
      <mesh
        geometry={nodes.sphere_67.geometry}
        material={materials["Objects Shader"]}
        position={[-0.973, -0.789, 0.111]}
        rotation={[-0.64, -1.41, 1.182]}
        scale={1.257}
      />
      <mesh
        geometry={nodes.sphere_69.geometry}
        material={materials["Objects Shader"]}
        position={[-0.757, -0.65, 0.092]}
        rotation={[-1.306, 0.041, 0.815]}
        scale={0.984}
      />
      <mesh
        geometry={nodes.sphere_71.geometry}
        material={materials["Objects Shader"]}
        position={[-0.608, -0.576, 0.068]}
        rotation={[-0.485, -1.103, 1.076]}
        scale={0.953}
      />
      <mesh
        geometry={nodes.sphere_73.geometry}
        material={materials["Objects Shader"]}
        position={[-0.656, -0.624, 0]}
        rotation={[-0.781, -0.924, 0.321]}
        scale={0.685}
      />
      <mesh
        geometry={nodes.sphere_75.geometry}
        material={materials["Objects Shader"]}
        position={[-0.652, -0.485, 0.103]}
        rotation={[-1.219, 0.214, -0.417]}
        scale={0.763}
      />
      <mesh
        geometry={nodes.sphere_77.geometry}
        material={materials["Objects Shader"]}
        position={[-0.547, -0.444, -0.014]}
        rotation={[-1.019, -1.162, 0.283]}
        scale={1.176}
      />
      <mesh
        geometry={nodes.sphere_79.geometry}
        material={materials["Objects Shader"]}
        position={[-0.589, -0.359, 0.053]}
        rotation={[-1.375, -1.191, 0.46]}
        scale={1.209}
      />
      <mesh
        geometry={nodes.sphere_81.geometry}
        material={materials["Objects Shader"]}
        position={[-0.752, -0.638, 0.055]}
        rotation={[-1.278, 0.022, 0.65]}
        scale={0.836}
      />
      <mesh
        geometry={nodes.sphere_83.geometry}
        material={materials["Objects Shader"]}
        position={[-0.89, -0.708, 0.015]}
        rotation={[-2.503, -1.356, -1.609]}
        scale={1.14}
      />
      <mesh
        geometry={nodes.sphere_85.geometry}
        material={materials["Objects Shader"]}
        position={[-0.639, -0.739, 0.062]}
        rotation={[-1.552, -0.704, 0.438]}
        scale={0.907}
      />
      <mesh
        geometry={nodes.sphere_87.geometry}
        material={materials["Objects Shader"]}
        position={[-0.713, -0.897, 0.059]}
        rotation={[-0.908, -1.203, 1.459]}
        scale={0.969}
      />
      <mesh
        geometry={nodes.sphere_89.geometry}
        material={materials["Objects Shader"]}
        position={[-0.534, -0.625, -0.001]}
        rotation={[-1.669, -1.314, 0.628]}
        scale={0.981}
      />
      <mesh
        geometry={nodes.sphere_91.geometry}
        material={materials["Objects Shader"]}
        position={[-0.456, -0.794, 0.108]}
        rotation={[-1.932, -0.273, -0.304]}
        scale={1.023}
      />
      <mesh
        geometry={nodes.sphere_93.geometry}
        material={materials["Objects Shader"]}
        position={[-0.573, -0.525, 0.084]}
        rotation={[2.031, -1.437, -2.269]}
        scale={0.983}
      />
      <mesh
        geometry={nodes.sphere_95.geometry}
        material={materials["Objects Shader"]}
        position={[-0.724, -0.859, 0.082]}
        rotation={[-1.519, -0.066, -0.961]}
        scale={0.881}
      />
      <mesh
        geometry={nodes.sphere_97.geometry}
        material={materials["Objects Shader"]}
        position={[-0.582, -0.835, 0.053]}
        rotation={[1.114, -1.333, -2.972]}
        scale={0.928}
      />
      <mesh
        geometry={nodes.sphere_99.geometry}
        material={materials["Objects Shader"]}
        position={[-0.283, -0.601, 0.076]}
        rotation={[-1.822, -0.055, -0.104]}
        scale={1.173}
      />
      <mesh
        geometry={nodes.sphere_101.geometry}
        material={materials["Objects Shader"]}
        position={[-0.441, -0.631, 0.12]}
        rotation={[2.758, -1.299, -2.57]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.sphere_103.geometry}
        material={materials["Objects Shader"]}
        position={[-0.593, -0.888, 0.091]}
        rotation={[0.566, -1.117, 1.293]}
        scale={0.906}
      />
      <mesh
        geometry={nodes.sphere_105.geometry}
        material={materials["Objects Shader"]}
        position={[-0.187, -0.887, 0.177]}
        rotation={[-1.359, -0.64, 0.708]}
        scale={1.127}
      />
      <mesh
        geometry={nodes.sphere_107.geometry}
        material={materials["Objects Shader"]}
        position={[-0.395, -0.653, 0.106]}
        rotation={[-2.078, -0.469, -0.48]}
        scale={0.616}
      />
      <mesh
        geometry={nodes.sphere_109.geometry}
        material={materials["Objects Shader"]}
        position={[-0.355, -0.894, 0.16]}
        rotation={[-1.834, -0.237, -0.509]}
        scale={0.809}
      />
      <mesh
        geometry={nodes.sphere_111.geometry}
        material={materials["Objects Shader"]}
        position={[-0.316, -0.78, 0.015]}
        rotation={[1.595, -1.075, -2.192]}
        scale={1.195}
      />
      <mesh
        geometry={nodes.sphere_113.geometry}
        material={materials["Objects Shader"]}
        position={[-0.172, -1.025, 0.084]}
        rotation={[-3.038, -1.388, -1.864]}
        scale={1.224}
      />
      <mesh
        geometry={nodes.sphere_115.geometry}
        material={materials["Objects Shader"]}
        position={[-0.418, -1.023, 0.177]}
        rotation={[-2.17, -0.818, -1.139]}
        scale={0.679}
      />
      <mesh
        geometry={nodes.sphere_117.geometry}
        material={materials["Objects Shader"]}
        position={[-0.263, -0.995, 0.109]}
        rotation={[-1.382, -0.878, 0.628]}
        scale={0.921}
      />
      <mesh
        geometry={nodes.sphere_119.geometry}
        material={materials["Objects Shader"]}
        position={[-0.208, -0.873, 0.063]}
        rotation={[1.955, -0.979, -3.053]}
        scale={1.28}
      />
      <mesh
        geometry={nodes.sphere_121.geometry}
        material={materials["Objects Shader"]}
        position={[-0.081, -1.033, 0.006]}
        rotation={[-2.022, -0.992, -0.741]}
        scale={0.928}
      />
      <mesh
        geometry={nodes.sphere_123.geometry}
        material={materials["Objects Shader"]}
        position={[-0.327, -0.998, 0.212]}
        rotation={[-2.215, -0.611, -0.571]}
        scale={0.919}
      />
      <mesh
        geometry={nodes.sphere_125.geometry}
        material={materials["Objects Shader"]}
        position={[-0.069, -1.255, 0.15]}
        rotation={[-2.98, -1.134, -0.991]}
        scale={0.618}
      />
      <mesh
        geometry={nodes.sphere_127.geometry}
        material={materials["Objects Shader"]}
        position={[0.027, -1.049, 0.038]}
        rotation={[-0.62, -1.205, 0.92]}
        scale={0.753}
      />
      <mesh
        geometry={nodes.sphere_129.geometry}
        material={materials["Objects Shader"]}
        position={[-0.022, -0.836, 0.056]}
        rotation={[-1.3, -0.573, 0.989]}
        scale={0.761}
      />
      <mesh
        geometry={nodes.sphere_131.geometry}
        material={materials["Objects Shader"]}
        position={[-0.041, -0.898, 0.026]}
        rotation={[-1.539, -0.842, -0.304]}
        scale={1.36}
      />
      <mesh
        geometry={nodes.sphere_133.geometry}
        material={materials["Objects Shader"]}
        position={[-0.128, -0.823, 0.055]}
        rotation={[-1.808, -1.012, -1.081]}
        scale={0.611}
      />
      <mesh
        geometry={nodes.sphere_135.geometry}
        material={materials["Objects Shader"]}
        position={[-0.145, -0.953, 0.089]}
        rotation={[1.814, -0.849, -1.99]}
        scale={0.655}
      />
      <mesh
        geometry={nodes.sphere_137.geometry}
        material={materials["Objects Shader"]}
        position={[0.248, -1.107, 0.046]}
        rotation={[-1.447, -1.346, -0.787]}
        scale={1.126}
      />
      <mesh
        geometry={nodes.sphere_139.geometry}
        material={materials["Objects Shader"]}
        position={[0.113, -0.946, 0.016]}
        rotation={[1.66, -0.761, 2.344]}
        scale={0.629}
      />
      <mesh
        geometry={nodes.sphere_141.geometry}
        material={materials["Objects Shader"]}
        position={[0.26, -0.811, 0.024]}
        rotation={[-2.034, -1.134, -1.164]}
        scale={1.181}
      />
      <mesh
        geometry={nodes.sphere_143.geometry}
        material={materials["Objects Shader"]}
        position={[0.038, -0.945, 0.073]}
        rotation={[-1.866, -1.055, 0.089]}
        scale={0.757}
      />
      <mesh
        geometry={nodes.sphere_145.geometry}
        material={materials["Objects Shader"]}
        position={[0.391, -1.17, 0.168]}
        rotation={[1.553, -0.913, -2.098]}
        scale={1.26}
      />
      <mesh
        geometry={nodes.sphere_147.geometry}
        material={materials["Objects Shader"]}
        position={[0.456, -1.025, 0.112]}
        rotation={[-0.914, -1.011, 0.659]}
        scale={1.187}
      />
      <mesh
        geometry={nodes.sphere_149.geometry}
        material={materials["Objects Shader"]}
        position={[0.125, -0.906, 0.08]}
        rotation={[1.78, -0.755, 2.975]}
        scale={0.689}
      />
      <mesh
        geometry={nodes.sphere_151.geometry}
        material={materials["Objects Shader"]}
        position={[0.427, -0.832, 0.104]}
        rotation={[-0.145, -1.129, 1.529]}
        scale={0.746}
      />
      <mesh
        geometry={nodes.sphere_153.geometry}
        material={materials["Objects Shader"]}
        position={[0.368, -1.048, 0.089]}
        rotation={[1.175, -0.639, -2.607]}
        scale={1.299}
      />
      <mesh
        geometry={nodes.sphere_155.geometry}
        material={materials["Objects Shader"]}
        position={[0.374, -0.689, 0.059]}
        rotation={[0.439, -1.376, 1.719]}
        scale={0.869}
      />
      <mesh
        geometry={nodes.sphere_157.geometry}
        material={materials["Objects Shader"]}
        position={[0.488, -1.177, 0.164]}
        rotation={[3.111, -1.15, -0.944]}
        scale={1.183}
      />
      <mesh
        geometry={nodes.sphere_159.geometry}
        material={materials["Objects Shader"]}
        position={[0.34, -0.904, 0.09]}
        rotation={[-2.809, -1.361, -0.239]}
        scale={1.308}
      />
      <mesh
        geometry={nodes.sphere_161.geometry}
        material={materials["Objects Shader"]}
        position={[0.611, -0.99, 0.069]}
        rotation={[2.888, -1.1, -1.38]}
        scale={1.031}
      />
      <mesh
        geometry={nodes.sphere_163.geometry}
        material={materials["Objects Shader"]}
        position={[0.488, -0.875, 0.106]}
        rotation={[-2.414, -1.163, -0.667]}
        scale={1.109}
      />
      <mesh
        geometry={nodes.sphere_165.geometry}
        material={materials["Objects Shader"]}
        position={[0.695, -0.847, 0.082]}
        rotation={[1.378, -0.349, -2.434]}
        scale={1.109}
      />
      <mesh
        geometry={nodes.sphere_167.geometry}
        material={materials["Objects Shader"]}
        position={[0.534, -0.624, 0.073]}
        rotation={[1.964, -0.65, 3.11]}
        scale={1.114}
      />
      <mesh
        geometry={nodes.sphere_169.geometry}
        material={materials["Objects Shader"]}
        position={[0.597, -0.824, 0.07]}
        rotation={[1.392, -0.267, -2.476]}
        scale={0.962}
      />
      <mesh
        geometry={nodes.sphere_171.geometry}
        material={materials["Objects Shader"]}
        position={[0.807, -0.751, 0.09]}
        rotation={[1.886, -0.332, 2.911]}
        scale={0.685}
      />
      <mesh
        geometry={nodes.sphere_173.geometry}
        material={materials["Objects Shader"]}
        position={[0.629, -0.753, 0.048]}
        rotation={[2.352, -0.961, -2.602]}
        scale={0.719}
      />
      <mesh
        geometry={nodes.sphere_175.geometry}
        material={materials["Objects Shader"]}
        position={[0.663, -0.657, 0.112]}
        rotation={[1.822, -0.979, 3.049]}
        scale={0.904}
      />
      <mesh
        geometry={nodes.sphere_177.geometry}
        material={materials["Objects Shader"]}
        position={[0.787, -0.739, 0.02]}
        rotation={[0.577, -1.086, 2.801]}
        scale={0.868}
      />
      <mesh
        geometry={nodes.sphere_179.geometry}
        material={materials["Objects Shader"]}
        position={[0.406, -0.544, 0.027]}
        rotation={[1.72, 0.126, 2.83]}
        scale={1.344}
      />
      <mesh
        geometry={nodes.sphere_181.geometry}
        material={materials["Objects Shader"]}
        position={[0.859, -0.649, 0.034]}
        rotation={[1.359, -1.031, 2.105]}
        scale={0.982}
      />
      <mesh
        geometry={nodes.sphere_183.geometry}
        material={materials["Objects Shader"]}
        position={[0.8, -0.847, 0.121]}
        rotation={[2.346, -1.357, 3.039]}
        scale={1.07}
      />
      <mesh
        geometry={nodes.sphere_185.geometry}
        material={materials["Objects Shader"]}
        position={[0.68, -0.554, 0.112]}
        rotation={[1.428, -0.1, 2.316]}
        scale={0.664}
      />
      <mesh
        geometry={nodes.sphere_187.geometry}
        material={materials["Objects Shader"]}
        position={[0.526, -0.719, 0.003]}
        rotation={[2.055, -0.493, 3.129]}
        scale={1.346}
      />
      <mesh
        geometry={nodes.sphere_189.geometry}
        material={materials["Objects Shader"]}
        position={[0.835, -0.554, -0.001]}
        rotation={[1.91, -0.114, 2.663]}
        scale={0.794}
      />
      <mesh
        geometry={nodes.sphere_191.geometry}
        material={materials["Objects Shader"]}
        position={[0.734, -0.51, 0.01]}
        rotation={[1.725, -0.361, 2.319]}
        scale={0.741}
      />
      <mesh
        geometry={nodes.sphere_193.geometry}
        material={materials["Objects Shader"]}
        position={[0.725, -0.613, 0.14]}
        rotation={[-2.855, -1.126, -1.388]}
        scale={1.152}
      />
      <mesh
        geometry={nodes.sphere_195.geometry}
        material={materials["Objects Shader"]}
        position={[0.747, -0.407, 0.023]}
        rotation={[1.818, -0.351, 2.316]}
        scale={0.887}
      />
      <mesh
        geometry={nodes.sphere_197.geometry}
        material={materials["Objects Shader"]}
        position={[0.62, -0.32, 0.026]}
        rotation={[1.248, -0.113, 2.668]}
        scale={1.283}
      />
      <mesh
        geometry={nodes.sphere_199.geometry}
        material={materials["Objects Shader"]}
        position={[0.881, -0.399, 0.018]}
        rotation={[1.226, 0.456, -3.005]}
        scale={0.771}
      />
      <mesh
        geometry={nodes.sphere_201.geometry}
        material={materials["Objects Shader"]}
        position={[0.79, -0.308, 0.044]}
        rotation={[1.814, -0.606, -2.461]}
        scale={0.69}
      />
      <mesh
        geometry={nodes.sphere_203.geometry}
        material={materials["Objects Shader"]}
        position={[0.708, -0.239, 0.066]}
        rotation={[1.02, 0.361, -2.668]}
        scale={1.044}
      />
      <mesh
        geometry={nodes.sphere_205.geometry}
        material={materials["Objects Shader"]}
        position={[0.803, -0.363, -0.046]}
        rotation={[1.484, -0.121, 2.126]}
        scale={1.225}
      />
      <mesh
        geometry={nodes.sphere_207.geometry}
        material={materials["Objects Shader"]}
        position={[1.154, -0.244, 0.044]}
        rotation={[1.439, -0.344, -2.878]}
        scale={1.016}
      />
      <mesh
        geometry={nodes.sphere_209.geometry}
        material={materials["Objects Shader"]}
        position={[0.998, -0.216, 0.012]}
        rotation={[1.683, -0.691, 2.697]}
        scale={1.348}
      />
      <mesh
        geometry={nodes.sphere_211.geometry}
        material={materials["Objects Shader"]}
        position={[1.139, -0.236, -0.022]}
        rotation={[1.692, -0.147, -3.106]}
        scale={1.004}
      />
      <mesh
        geometry={nodes.sphere_213.geometry}
        material={materials["Objects Shader"]}
        position={[0.972, -0.383, 0.053]}
        rotation={[1.717, 0.269, -2.681]}
        scale={1.146}
      />
      <mesh
        geometry={nodes.sphere_215.geometry}
        material={materials["Objects Shader"]}
        position={[1.033, -0.101, 0.037]}
        rotation={[1.378, -0.139, -2.628]}
        scale={0.725}
      />
      <mesh
        geometry={nodes.sphere_217.geometry}
        material={materials["Objects Shader"]}
        position={[0.94, -0.248, -0.041]}
        rotation={[1.096, -0.763, 3.006]}
        scale={1.364}
      />
      <mesh
        geometry={nodes.sphere_219.geometry}
        material={materials["Objects Shader"]}
        position={[0.999, 0.001, 0.007]}
        rotation={[1.859, -0.02, 2.702]}
        scale={0.797}
      />
      <mesh
        geometry={nodes.sphere_221.geometry}
        material={materials["Objects Shader"]}
        position={[0.778, -0.189, 0.048]}
        rotation={[1.541, -0.73, -2.814]}
        scale={0.939}
      />
      <mesh
        geometry={nodes.sphere_223.geometry}
        material={materials["Objects Shader"]}
        position={[0.922, -0.095, -0.01]}
        rotation={[1.732, -0.205, -2.969]}
        scale={1.222}
      />
      <mesh
        geometry={nodes.sphere_225.geometry}
        material={materials["Objects Shader"]}
        position={[0.804, 0.027, 0.016]}
        rotation={[1.06, 0.43, 2.459]}
        scale={1.109}
      />
      <mesh
        geometry={nodes.sphere_227.geometry}
        material={materials["Objects Shader"]}
        position={[1.118, -0.11, -0.004]}
        rotation={[1.848, -0.991, -2.945]}
        scale={0.735}
      />
      <mesh
        geometry={nodes.sphere_229.geometry}
        material={materials["Objects Shader"]}
        position={[1.009, -0.079, -0.046]}
        rotation={[1.495, -0.295, 2.847]}
        scale={1.367}
      />
      <mesh
        geometry={nodes.sphere_231.geometry}
        material={materials["Objects Shader"]}
        position={[1.207, 0.199, -0.055]}
        rotation={[1.091, -0.391, -2.685]}
        scale={1.288}
      />
      <mesh
        geometry={nodes.sphere_233.geometry}
        material={materials["Objects Shader"]}
        position={[1.06, 0.106, -0.008]}
        rotation={[2.158, 0.916, 1.832]}
        scale={0.942}
      />
      <mesh
        geometry={nodes.sphere_235.geometry}
        material={materials["Objects Shader"]}
        position={[1.09, -0.035, -0.05]}
        rotation={[1.881, 0.502, 2.1]}
        scale={0.743}
      />
      <mesh
        geometry={nodes.sphere_237.geometry}
        material={materials["Objects Shader"]}
        position={[0.783, -0.05, 0.047]}
        rotation={[1.615, -0.337, 2.585]}
        scale={0.675}
      />
      <mesh
        geometry={nodes.sphere_239.geometry}
        material={materials["Objects Shader"]}
        position={[1.173, 0.053, 0.04]}
        rotation={[1.107, 0.045, 2.777]}
        scale={1.251}
      />
      <mesh
        geometry={nodes.sphere_241.geometry}
        material={materials["Objects Shader"]}
        position={[0.777, 0.289, -0.011]}
        rotation={[0.816, 0.677, -1.803]}
        scale={1.372}
      />
      <mesh
        geometry={nodes.sphere_243.geometry}
        material={materials["Objects Shader"]}
        position={[1.123, 0.355, -0.131]}
        rotation={[1.193, -0.312, 2.552]}
        scale={1.194}
      />
      <mesh
        geometry={nodes.sphere_245.geometry}
        material={materials["Objects Shader"]}
        position={[0.883, 0.307, -0.019]}
        rotation={[2.132, 0.608, 2.945]}
        scale={0.702}
      />
      <mesh
        geometry={nodes.sphere_247.geometry}
        material={materials["Objects Shader"]}
        position={[0.939, 0.168, 0.034]}
        rotation={[1.828, -0.594, -2.873]}
        scale={1.364}
      />
      <mesh
        geometry={nodes.sphere_249.geometry}
        material={materials["Objects Shader"]}
        position={[0.798, 0.13, -0.039]}
        rotation={[1.28, 1.064, -2.848]}
        scale={0.718}
      />
      <mesh
        geometry={nodes.sphere_251.geometry}
        material={materials["Objects Shader"]}
        position={[0.69, 0.207, 0.012]}
        rotation={[0.614, 0.928, -2.399]}
        scale={1.245}
      />
      <mesh
        geometry={nodes.sphere_253.geometry}
        material={materials["Objects Shader"]}
        position={[1.056, 0.492, 0.051]}
        rotation={[1.709, -0.049, -2.395]}
        scale={0.883}
      />
      <mesh
        geometry={nodes.sphere_255.geometry}
        material={materials["Objects Shader"]}
        position={[0.992, 0.277, 0.039]}
        rotation={[1.691, -0.152, 2.558]}
        scale={0.894}
      />
      <mesh
        geometry={nodes.sphere_257.geometry}
        material={materials["Objects Shader"]}
        position={[0.639, 0.438, -0.077]}
        rotation={[1.507, 1.098, -2.79]}
        scale={0.663}
      />
      <mesh
        geometry={nodes.sphere_259.geometry}
        material={materials["Objects Shader"]}
        position={[0.78, 0.203, 0.026]}
        rotation={[1.63, -0.597, -2.293]}
        scale={1.069}
      />
      <mesh
        geometry={nodes.sphere_261.geometry}
        material={materials["Objects Shader"]}
        position={[0.812, 0.499, -0.054]}
        rotation={[1.75, 0.584, 2.859]}
        scale={0.968}
      />
      <mesh
        geometry={nodes.sphere_263.geometry}
        material={materials["Objects Shader"]}
        position={[0.639, 0.347, -0.009]}
        rotation={[1.177, 0.003, -2.865]}
        scale={1.104}
      />
      <mesh
        geometry={nodes.sphere_265.geometry}
        material={materials["Objects Shader"]}
        position={[0.762, 0.488, 0.01]}
        rotation={[1.948, 0.261, 2.629]}
        scale={1.321}
      />
      <mesh
        geometry={nodes.sphere_267.geometry}
        material={materials["Objects Shader"]}
        position={[0.847, 0.394, -0.052]}
        rotation={[1.93, 1.157, 2.436]}
        scale={0.79}
      />
      <mesh
        geometry={nodes.sphere_269.geometry}
        material={materials["Objects Shader"]}
        position={[0.749, 0.599, -0.096]}
        rotation={[2.046, 0.874, 2.827]}
        scale={1.223}
      />
      <mesh
        geometry={nodes.sphere_271.geometry}
        material={materials["Objects Shader"]}
        position={[0.838, 0.638, -0.079]}
        rotation={[1.422, 0.514, 2.571]}
        scale={0.94}
      />
      <mesh
        geometry={nodes.sphere_273.geometry}
        material={materials["Objects Shader"]}
        position={[0.853, 0.683, -0.099]}
        rotation={[2.509, 0.955, 1.512]}
        scale={0.991}
      />
      <mesh
        geometry={nodes.sphere_275.geometry}
        material={materials["Objects Shader"]}
        position={[0.683, 0.767, -0.003]}
        rotation={[1.534, 0.417, -2.972]}
        scale={0.919}
      />
      <mesh
        geometry={nodes.sphere_277.geometry}
        material={materials["Objects Shader"]}
        position={[0.546, 0.627, -0.007]}
        rotation={[0.988, -0.024, 2.394]}
        scale={0.945}
      />
      <mesh
        geometry={nodes.sphere_279.geometry}
        material={materials["Objects Shader"]}
        position={[0.705, 0.6, -0.116]}
        rotation={[1.789, 0.496, 2.735]}
        scale={0.611}
      />
      <mesh
        geometry={nodes.sphere_281.geometry}
        material={materials["Objects Shader"]}
        position={[0.936, 0.655, -0.026]}
        rotation={[-1.8, 1.423, -0.386]}
        scale={0.618}
      />
      <mesh
        geometry={nodes.sphere_283.geometry}
        material={materials["Objects Shader"]}
        position={[0.685, 0.513, -0.041]}
        rotation={[1.733, 1.051, -2.437]}
        scale={1.087}
      />
      <mesh
        geometry={nodes.sphere_285.geometry}
        material={materials["Objects Shader"]}
        position={[0.723, 0.838, -0.138]}
        rotation={[1.693, 0.937, 2.211]}
        scale={0.867}
      />
      <mesh
        geometry={nodes.sphere_287.geometry}
        material={materials["Objects Shader"]}
        position={[0.683, 0.922, -0.086]}
        rotation={[-0.724, 1.046, -0.036]}
        scale={1.077}
      />
      <mesh
        geometry={nodes.sphere_289.geometry}
        material={materials["Objects Shader"]}
        position={[0.766, 0.992, -0.138]}
        rotation={[1.644, -0.022, -2.232]}
        scale={0.952}
      />
      <mesh
        geometry={nodes.sphere_291.geometry}
        material={materials["Objects Shader"]}
        position={[0.38, 0.637, -0.103]}
        rotation={[2.483, 1.195, 1.241]}
        scale={1.08}
      />
      <mesh
        geometry={nodes.sphere_293.geometry}
        material={materials["Objects Shader"]}
        position={[0.463, 0.891, -0.145]}
        rotation={[2.316, 1.195, 1.789]}
        scale={0.671}
      />
      <mesh
        geometry={nodes.sphere_295.geometry}
        material={materials["Objects Shader"]}
        position={[0.569, 0.88, -0.091]}
        rotation={[1.683, 0.099, -3.03]}
        scale={1.032}
      />
      <mesh
        geometry={nodes.sphere_297.geometry}
        material={materials["Objects Shader"]}
        position={[0.474, 0.518, -0.049]}
        rotation={[-3.071, 1.175, 1.081]}
        scale={1.209}
      />
      <mesh
        geometry={nodes.sphere_299.geometry}
        material={materials["Objects Shader"]}
        position={[0.461, 0.638, -0.081]}
        rotation={[0.845, 1.015, -2.163]}
        scale={0.971}
      />
      <mesh
        geometry={nodes.sphere_301.geometry}
        material={materials["Objects Shader"]}
        position={[0.281, 0.654, -0.053]}
        rotation={[2.001, 0.248, -2.251]}
        scale={1.196}
      />
      <mesh
        geometry={nodes.sphere_303.geometry}
        material={materials["Objects Shader"]}
        position={[0.508, 1.109, -0.163]}
        rotation={[1.65, 0.372, 2.57]}
        scale={0.99}
      />
      <mesh
        geometry={nodes.sphere_305.geometry}
        material={materials["Objects Shader"]}
        position={[0.423, 0.982, -0.14]}
        rotation={[0.375, 1.095, -2.823]}
        scale={0.828}
      />
      <mesh
        geometry={nodes.sphere_307.geometry}
        material={materials["Objects Shader"]}
        position={[0.212, 0.925, -0.056]}
        rotation={[-2.155, 0.707, -0.641]}
        scale={1.158}
      />
      <mesh
        geometry={nodes.sphere_309.geometry}
        material={materials["Objects Shader"]}
        position={[0.417, 0.829, -0.049]}
        rotation={[2.587, 1.185, 1.595]}
        scale={0.946}
      />
      <mesh
        geometry={nodes.sphere_311.geometry}
        material={materials["Objects Shader"]}
        position={[0.181, 0.971, -0.14]}
        rotation={[1.945, 0.551, 2.606]}
        scale={0.866}
      />
      <mesh
        geometry={nodes.sphere_313.geometry}
        material={materials["Objects Shader"]}
        position={[0.297, 1.105, -0.131]}
        rotation={[2.631, 1.089, 2.386]}
        scale={1.132}
      />
      <mesh
        geometry={nodes.sphere_315.geometry}
        material={materials["Objects Shader"]}
        position={[0.408, 1.122, -0.195]}
        rotation={[2.745, 1.358, 1.256]}
        scale={0.696}
      />
      <mesh
        geometry={nodes.sphere_317.geometry}
        material={materials["Objects Shader"]}
        position={[0.08, 1.059, -0.172]}
        rotation={[-2.384, 1.222, -0.172]}
        scale={1.304}
      />
      <mesh
        geometry={nodes.sphere_319.geometry}
        material={materials["Objects Shader"]}
        position={[0.388, 1.051, -0.126]}
        rotation={[-2.835, 1.023, 1.351]}
        scale={0.665}
      />
      <mesh
        geometry={nodes.sphere_321.geometry}
        material={materials["Objects Shader"]}
        position={[0.303, 0.849, -0.041]}
        rotation={[2.131, 0.657, 2.616]}
        scale={1.287}
      />
      <mesh
        geometry={nodes.sphere_323.geometry}
        material={materials["Objects Shader"]}
        position={[0.222, 1.157, -0.076]}
        rotation={[-1.646, 0.756, -0.337]}
        scale={1.134}
      />
      <mesh
        geometry={nodes.sphere_325.geometry}
        material={materials["Objects Shader"]}
        position={[-0.013, 1.05, -0.121]}
        rotation={[-2.659, 1.158, 1.596]}
        scale={1.233}
      />
      <mesh
        geometry={nodes.sphere_327.geometry}
        material={materials["Objects Shader"]}
        position={[-0.1, 1.182, -0.144]}
        rotation={[-1.523, 0.535, -0.661]}
        scale={1.06}
      />
      <mesh
        geometry={nodes.sphere_329.geometry}
        material={materials["Objects Shader"]}
        position={[-0.107, 0.748, -0.109]}
        rotation={[0.178, 1.507, -2.509]}
        scale={1.36}
      />
      <mesh
        geometry={nodes.sphere_331.geometry}
        material={materials["Objects Shader"]}
        position={[-0.156, 0.984, 0.009]}
        rotation={[0.862, 0.664, -1.732]}
        scale={0.645}
      />
      <mesh
        geometry={nodes.sphere_333.geometry}
        material={materials["Objects Shader"]}
        position={[-0.127, 1.086, -0.04]}
        rotation={[0.901, 0.888, -2.126]}
        scale={0.695}
      />
      <mesh
        geometry={nodes.sphere_335.geometry}
        material={materials["Objects Shader"]}
        position={[0.061, 0.952, -0.125]}
        rotation={[-1.697, 0.682, -0.028]}
        scale={0.683}
      />
      <mesh
        geometry={nodes.sphere_337.geometry}
        material={materials["Objects Shader"]}
        position={[-0.068, 1.274, -0.153]}
        rotation={[2.364, 1.401, 3.073]}
        scale={1.282}
      />
      <mesh
        geometry={nodes.sphere_339.geometry}
        material={materials["Objects Shader"]}
        position={[-0.044, 1.049, -0.05]}
        rotation={[1.312, 1.152, -2.532]}
        scale={0.863}
      />
      <mesh
        geometry={nodes.sphere_341.geometry}
        material={materials["Objects Shader"]}
        position={[-0.133, 1.15, -0.138]}
        rotation={[-1.994, 0.855, -0.367]}
        scale={0.753}
      />
      <mesh
        geometry={nodes.sphere_343.geometry}
        material={materials["Objects Shader"]}
        position={[-0.225, 1.251, -0.051]}
        rotation={[0.501, 1.153, -1.829]}
        scale={1.307}
      />
      <mesh
        geometry={nodes.sphere_345.geometry}
        material={materials["Objects Shader"]}
        position={[0.039, 0.791, -0.123]}
        rotation={[-2.439, 1.239, 1.107]}
        scale={1.303}
      />
      <mesh
        geometry={nodes.sphere_347.geometry}
        material={materials["Objects Shader"]}
        position={[-0.176, 0.881, -0.105]}
        rotation={[1.076, 1.363, -2.909]}
        scale={0.82}
      />
      <mesh
        geometry={nodes.sphere_349.geometry}
        material={materials["Objects Shader"]}
        position={[-0.238, 0.948, -0.036]}
        rotation={[-2.451, 1.172, 1.036]}
        scale={1.184}
      />
      <mesh
        geometry={nodes.sphere_351.geometry}
        material={materials["Objects Shader"]}
        position={[-0.463, 1.034, -0.031]}
        rotation={[2.545, 1.107, 1.978]}
        scale={0.927}
      />
      <mesh
        geometry={nodes.sphere_353.geometry}
        material={materials["Objects Shader"]}
        position={[-0.296, 1.106, -0.131]}
        rotation={[1.995, 1.2, 3.065]}
        scale={0.754}
      />
      <mesh
        geometry={nodes.sphere_355.geometry}
        material={materials["Objects Shader"]}
        position={[-0.509, 0.911, -0.132]}
        rotation={[-2.154, 0.142, 0.427]}
        scale={1.173}
      />
      <mesh
        geometry={nodes.sphere_357.geometry}
        material={materials["Objects Shader"]}
        position={[-0.386, 1.208, -0.077]}
        rotation={[1.207, 1.001, -2.812]}
        scale={1.188}
      />
      <mesh
        geometry={nodes.sphere_359.geometry}
        material={materials["Objects Shader"]}
        position={[-0.513, 0.76, -0.031]}
        rotation={[-1.792, 0.372, -0.332]}
        scale={1.151}
      />
      <mesh
        geometry={nodes.sphere_361.geometry}
        material={materials["Objects Shader"]}
        position={[-0.273, 1.017, -0.149]}
        rotation={[-0.848, 1.046, -0.54]}
        scale={0.706}
      />
      <mesh
        geometry={nodes.sphere_363.geometry}
        material={materials["Objects Shader"]}
        position={[-0.591, 1.022, -0.066]}
        rotation={[2.622, 1.129, 2.343]}
        scale={1.148}
      />
      <mesh
        geometry={nodes.sphere_365.geometry}
        material={materials["Objects Shader"]}
        position={[-0.468, 0.899, -0.073]}
        rotation={[-2.255, 1.046, 0.484]}
        scale={0.797}
      />
      <mesh
        geometry={nodes.sphere_367.geometry}
        material={materials["Objects Shader"]}
        position={[-0.71, 0.976, -0.175]}
        rotation={[-1.545, 0.676, 0.961]}
        scale={0.877}
      />
      <mesh
        geometry={nodes.sphere_369.geometry}
        material={materials["Objects Shader"]}
        position={[-0.443, 0.832, -0.076]}
        rotation={[-1.845, 0.395, -0.435]}
        scale={0.928}
      />
      <mesh
        geometry={nodes.sphere_371.geometry}
        material={materials["Objects Shader"]}
        position={[-0.598, 0.859, -0.048]}
        rotation={[-1.738, 0.098, -0.253]}
        scale={0.965}
      />
      <mesh
        geometry={nodes.sphere_373.geometry}
        material={materials["Objects Shader"]}
        position={[-0.638, 0.622, -0.045]}
        rotation={[-0.258, 1.311, -1.386]}
        scale={1.384}
      />
      <mesh
        geometry={nodes.sphere_375.geometry}
        material={materials["Objects Shader"]}
        position={[-0.809, 0.815, -0.115]}
        rotation={[-1.029, 1.081, -0.393]}
        scale={1.083}
      />
      <mesh
        geometry={nodes.sphere_377.geometry}
        material={materials["Objects Shader"]}
        position={[-0.552, 0.608, -0.014]}
        rotation={[-2.053, 0.468, 1.162]}
        scale={0.749}
      />
      <mesh
        geometry={nodes.sphere_379.geometry}
        material={materials["Objects Shader"]}
        position={[-0.704, 0.751, -0.06]}
        rotation={[3.028, 1.07, 1.306]}
        scale={0.98}
      />
      <mesh
        geometry={nodes.sphere_381.geometry}
        material={materials["Objects Shader"]}
        position={[-0.688, 0.631, -0.046]}
        rotation={[-1.983, -0.265, -0.988]}
        scale={1.272}
      />
      <mesh
        geometry={nodes.sphere_383.geometry}
        material={materials["Objects Shader"]}
        position={[-0.888, 0.61, -0.108]}
        rotation={[-2.11, -0.352, -0.134]}
        scale={0.709}
      />
      <mesh
        geometry={nodes.sphere_385.geometry}
        material={materials["Objects Shader"]}
        position={[-0.941, 0.572, -0.123]}
        rotation={[-1.895, -0.393, 0.828]}
        scale={0.615}
      />
      <mesh
        geometry={nodes.sphere_387.geometry}
        material={materials["Objects Shader"]}
        position={[-0.891, 0.764, -0.06]}
        rotation={[-1.789, 1.198, 0.234]}
        scale={0.713}
      />
      <mesh
        geometry={nodes.sphere_389.geometry}
        material={materials["Objects Shader"]}
        position={[-0.713, 0.509, -0.067]}
        rotation={[-0.481, 1.09, -1.758]}
        scale={0.845}
      />
      <mesh
        geometry={nodes.sphere_391.geometry}
        material={materials["Objects Shader"]}
        position={[-0.601, 0.423, -0.05]}
        rotation={[-1.342, 0.44, 0.246]}
        scale={1.243}
      />
      <mesh
        geometry={nodes.sphere_393.geometry}
        material={materials["Objects Shader"]}
        position={[-1, 0.704, -0.098]}
        rotation={[-1.253, 0.947, -0.911]}
        scale={1.15}
      />
      <mesh
        geometry={nodes.sphere_395.geometry}
        material={materials["Objects Shader"]}
        position={[-0.764, 0.461, 0.021]}
        rotation={[-1.552, -0.163, 0.545]}
        scale={0.989}
      />
      <mesh
        geometry={nodes.sphere_397.geometry}
        material={materials["Objects Shader"]}
        position={[-1.022, 0.346, -0.049]}
        rotation={[-1.646, 0.177, -0.846]}
        scale={1.156}
      />
      <mesh
        geometry={nodes.sphere_399.geometry}
        material={materials["Objects Shader"]}
        position={[-0.704, 0.255, -0.114]}
        rotation={[-0.974, 0.992, -1.585]}
        scale={0.802}
      />
    </group>
  );
}

useGLTF.preload("/Irys-Banner-Shapes-2.gltf");
